### ISSUE TITLE
Allow specifying a file location for the .gitlab.nvim file

### ISSUE THREAD

**Issue by briandipalma** [harrisoncramer/gitlab.nvim#116]
## Feature Description

I use worktrees and thus the file isn't present in the worktree when I create one to review colleagues work. It's basically like a whole new copy of the repository but quite fast. So it would be good if you could specify a file location for the `.gitlab.nvim` file or you could parse the git config and use the credentials file if there is one:

git config file:
```
[credential]
    helper = store --file ~/dev/my-data/.git-credentials
```

.git-credentials file:

```
https://$USERNAME:$AUTH_TOKEN@$URL
```

Obviously specifying a file location is much easier and I'd be more than happy with that TBH.

**Comment by harrisoncramer** [comment]
Hello, please try #117 to see if it works for you.

You can try this version of the plugin by providing a specific `branch` option if you are using Lazy or Packer, e.g. with Lazy it looks like this:

```lua
return {
  "harrisoncramer/gitlab.nvim",
  branch = "116-allow-specifying-a-file-location-for-the-gitlabnvim-file",
  dependencies = {
    "MunifTanjim/nui.nvim",
   ...
```

Does this work for you?

**Comment by briandipalma** [comment]
Works great, thanks!
