### ISSUE TITLE
How to start the gitlab.nvim server?

### ISSUE THREAD

**Issue by Otterpatsch** [harrisoncramer/gitlab.nvim#12]
Hey,

So im trying to use the the plugin with the self-host branch, but i get an error as soon as i jump into nvim.  
```
The gitlab.nvim server did not respond
Ran command: /home/eisbergsalat/.local/share/nvim/site/pack/packer/start/gitlab.nvim/bin 22 <selfhosted url> 21036 <mytoken>
```
.site/pack/packer/start/plenary.nvim/lua/plenary/curl.lua:274: get localhost:21036/info - curl error exit_code=7 stderr={ "curl: (7) Failed to connect to localhost port 21036 after 0 ms: Couldn't connect to server" } `

So i assume it has something to do with my configugration. Im using Packer but also willing to swap to Lazy as i basically swap to the first because of this package.

the gitlab.nvim related part in the plugins.lua
```  
use {
  'harrisoncramer/gitlab.nvim',
        branch = 'self-hosted',
  requires = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim"
  },
  run = function() require("gitlab").build() end,
  config = function()
                require("gitlab").setup(
{
  base_branch = "main",
  port = 20136, -- The port of the Go server, which runs in the background
  keymaps = {
    popup = { -- The popup for comment creation, editing, and replying
      exit = "<Esc>",
      perform_action = "<leader>s", -- Once in normal mode, does action
    },
    discussion_tree = { -- The discussion tree that holds all comments
      jump_to_location = "o",
      edit_comment = "e",
      delete_comment = "dd",
      reply_to_comment = "r",
      toggle_node = "t",
    },
    dialogue = { -- The confirmation dialogue for deleting comments
      focus_next = { "j", "<Down>", "<Tab>" },
      focus_prev = { "k", "<Up>", "<S-Tab>" },
      close = { "<Esc>", "<C-c>" },
      submit = { "<CR>", "<Space>" },
    }
  }
}
                        )
  end,
}
``` 
the .gitlab.nvim

```
project_id=22
auth_token=nicetoken
gitlab_url=selfhostedurl
base_branch=main
```
Btw it seems export AUTH_TOKEN isnt accepted. As inside nvim i get the error that auth_token is not set.

Im getting an error `editor command not found` if im trying to use any commands specified in https://github.com/harrisoncramer/gitlab.nvim#usage

I have the following go version installed
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/29692215/66b2f973-a637-429c-ab5a-69e11d0ae9a0)

**Comment by harrisoncramer** [comment]
Self-hosted Gitlab instances are not yet supported, you can follow along in that other thread for work on that, no need to open a new one. I'm quite busy at my day job, so I've not been able to prioritize getting that functionality.

However, your configuration is also wrong. You are supposed to check out the branch you want to review via git (like `git checkout feature-branch` in the terminal) _prior to opening Neovim_. Your Packer configuration wouldn't specify a branch "self-hosted" in your config.

**Comment by Otterpatsch** [comment]
> However, your configuration is also wrong. You are supposed to check out the branch you want to review via git (like git checkout feature-branch in the terminal) prior to opening Neovim. Your Packer configuration wouldn't specify a branch "self-hosted" in your config.

With 
```use {
  'harrisoncramer/gitlab.nvim',
        branch = 'self-hosted',
  requires = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim"
  },```
  Im trying there to use the branch of your repo (https://github.com/harrisoncramer/gitlab.nvim/tree/self-hosted). At least thats what packer tells me to specify if i want to use another branch than the main/master branch of a package.
