### ISSUE TITLE
Simplify suggested keybindings

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#122]
## Feature Description
The README suggests some keybindings for many functions of the plugin. Some of them are quite long, e.g., `"<leader>glaa"`. Even the four keystrokes in `"<leader>glr"` are quite a lot to type (yes, I'm lazy :)). A natural alternative seems to be dropping the `<leader>` prefix. The keycombination `gl` does not seem to have a special meaning in vanilla Vim and chances are that not many users use that keybinding for other things - I use a *lot* of plugins with a lot of keymaps and I was surprised to find out that `gl` is free to be used as a prefix for `gitlab.nvim`.

So I'd suggest to simply use this in the README.md:

````
```lua
local gitlab = require("gitlab")
vim.keymap.set("n", "glr", gitlab.review)
vim.keymap.set("n", "gls", gitlab.summary)
vim.keymap.set("n", "glA", gitlab.approve)
vim.keymap.set("n", "glR", gitlab.revoke)
vim.keymap.set("n", "glc", gitlab.create_comment)
vim.keymap.set("v", "glc", gitlab.create_multiline_comment)
vim.keymap.set("v", "glC", gitlab.create_comment_suggestion)
vim.keymap.set("n", "glm", gitlab.move_to_discussion_tree_from_diagnostic)
vim.keymap.set("n", "gln", gitlab.create_note)
vim.keymap.set("n", "gld", gitlab.toggle_discussions)
vim.keymap.set("n", "glaa", gitlab.add_assignee)
vim.keymap.set("n", "glad", gitlab.delete_assignee)
vim.keymap.set("n", "glra", gitlab.add_reviewer)
vim.keymap.set("n", "glrd", gitlab.delete_reviewer)
vim.keymap.set("n", "glp", gitlab.pipeline)
vim.keymap.set("n", "glo", gitlab.open_in_browser)
```
````

Well, since you @harrisoncramer say in the README that you are using the `<leader>` prefix for the mappings, it seems likely that you use `gl` for something else, in that case just close this issue right away :)

**Comment by harrisoncramer** [comment]
Yeah I can make this change no problem, thanks for the suggestion.

**Comment by harrisoncramer** [comment]
@jakubbortlik Can you do this as part of your other MR adjusting the README please?
