### ISSUE TITLE
Update git project info when switching to another feature branch after `gitlab.nvim` server started.

### ISSUE THREAD

**Issue by mars90226** [harrisoncramer/gitlab.nvim#125]
## Feature Description
Currently, `gitlab.nvim` server fetch the git project info on start and doesn't refresh afterward. This means reviewing another merge request can only be done by either:
1. Close neovim, switch to another feature branch, and start neovim.
2. Switch to another feature branch, kill the `gitlab.nvim` server, and manually start `gitlab.nvim` with `:lua require("gitlab.server").start(function() end)`.

I think neither both methods are ideal. It would be great if `gitlab.nvim` can provide either:
1. `gitlab.nvim` server can refresh git project info after receiving command.
2. `gitlab.nvim` provide a way (a command or function) to restart `gitlab.nvim` server.

Thank you.

**Comment by jakubbortlik** [comment]
I would find it similarly useful to be able to shut down the server and to clean up all the buffers the plugin has created. Something similar to `DiffviewClose`.

**Comment by harrisoncramer** [comment]
This MR will add the ability to shutdown and restart commands for the Go server:

https://github.com/harrisoncramer/gitlab.nvim/pull/120

These will be like other `server` commands in `gitlab.nvim` that can be called like this:

```lua
require("gitlab.server").restart() 
require("gitlab.server").shutdown()
```

For instance, to close the server and the reviewer pane at the same time you could do this:

```lua
 vim.keymap.set("n", "glK", function () 
  require("gitlab.server").shutdown()
  vim.cmd.tabclose()
end)
```

If you wanted to call this functionality in some sort of post-checkout hook, you could do that, which could allow you to restart the `gitlab.nvim` server after you check out a new branch.

**Comment by harrisoncramer** [comment]
Hey @mars90226 you should have the functionality you need now in v1.0.11! 

Please check the section of the Readme that talks about shutting down or restarting the server: https://github.com/harrisoncramer/gitlab.nvim#restarting-or-shutting-down

Does this resolve your issue?

**Comment by mars90226** [comment]
Sorry for the late response. Thank you, I'll try this soon!

I wrote a small lua function to kill the server & start it myself. But it cause gitlab.nvim to print error logs & break comment feature. So I'm glad you implement this so fast 😆

**Comment by mars90226** [comment]
I can confirm this does restart & comment feature is working. Thank you!
