### ISSUE TITLE
Filter discussion on username and thread status

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#126]
## Feature Description
It would be nice to be able to filter discussions based on `Username` and `status` (resolved vs unresolved). Ideally the filter could be toggled on and off easily while keeping the filter settings.

This is probably out of scope for #102, but I'm mentioning that PR here as I imagine filtering might be something to keep in mind when implementing the discussion tree.

**Comment by johnybx** [comment]
:wave: Hi,
currently this plugin support these:
```lua
  discussion_sign_and_diagnostic = {
    skip_resolved_discussion = false,
    skip_old_revision_discussion = true,
  },
```
so you can actually already filter by status ( the `skip_old_revision_discussion` had bug which I fixed in #102 ). Filtering itself shouldn't be problem :thinking:, having reasonable interface to set / update filters is probably more challenging.

**Comment by jakubbortlik** [comment]
Hi @johnybx I am aware of the `discussion_sign_and_diagnostic` option, but if I'm not mistaken this only affects the signs and diagnostics in the reviewer pane. I'd like to filter the discussion tree. Currently I work around this by having keymaps that can take me to e.g. the next unresolved thread, next unresolved thread created by me, etc. But it is unpractical to have eight different keymaps for moving around the tree.

I imagine filtering by author could have a similar interface as picking reviewers/asignees. The winbar that Harrison is experimenting with in #133 could be used to show the information about existing filters. However, I haven't got a clear idea of how to organize the information about resolved/unresolved threads and possible filters.

**Comment by harrisoncramer** [comment]
We can work real-time discussion/note filtering into a subsequent MR, #133 is good to review now Jakub and if that works we can add filtering logic as a follow-up.

**Comment by harrisoncramer** [comment]
This isn't something that I plan to implement but if someone is interested in adding this functionality they are more than welcome to and I can help review.
