### ISSUE TITLE
Could not install gitlab.nvim

### ISSUE THREAD

**Issue by xbladesub** [harrisoncramer/gitlab.nvim#13]
<img width="662" alt="Screenshot 2023-08-04 at 10 12 29 AM" src="https://github.com/harrisoncramer/gitlab.nvim/assets/45129790/8de4ddc3-09fa-49aa-be12-cc35e036fb22">

config (Lazy):

```lua
		{
			"harrisoncramer/gitlab.nvim",
			dependencies = {
				"MunifTanjim/nui.nvim",
				"nvim-lua/plenary.nvim",
			},
			build = function()
				require("gitlab").build()
			end, -- Builds the Go binary
			config = function()
				require("gitlab").setup()
			end,
		},
```

env variable set.

How to fix it?

**Comment by harrisoncramer** [comment]
This means that gitlab.nvim could not install the binary. Do you have Go installed? 
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/2d008624-69e6-4fef-a40b-4aecefe1b632)

**Comment by harrisoncramer** [comment]
What happens when you `cd` into the folder containing the plugin that's been cloned from Github and run `make` manually?

**Comment by harrisoncramer** [comment]
I'm going to close this today since I haven't back on the above! Make sure you have the latest version of the plugin, and have Go installed. If you still have issues you can comment on this issue again, I'll see it.
