### ISSUE TITLE
Enable showing notes independently from discussions

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#130]
## Feature Description
I'd like to be able to disable the `notes` panel in my configuration, and ideally be notified in some way if some notes happen to be present in the MR. 

In the projects that I work on, we rarely have notes so mostly when I run `toggle_discussions` I want the focus to go to the `discussions` and I don't want to see the `notes` panel at all. But instead, after toggling discussions, the focus goes to the `notes` and each time I have to make an extra step to navigate to the `discussions`.

One way of making the user aware of notes even if the `notes` panel were closed would be to put a `winbar` on the `discussions` panel, that would contain this information (it could maybe even show a simple statistics like the number of resolved and unresolved threads/notes). This could also be the place for showing information on possible filters that I talk about in #126.

**Comment by harrisoncramer** [comment]
Hey @jakubbortlik this should be addressed by #133 which does a number of different things including:

- Show notes and comments separately, with the ability to toggle between views
- Auto open split with the reviewer
- Adds help popups for local keybindings to different views

Please try out this branch and let me know if it addresses your request.

**Comment by jakubbortlik** [comment]
I've added my notes to the respective issue. I believe you can close this one.
