### ISSUE TITLE
Bug: Cannot Connect w/ Port in URL

### ISSUE THREAD

**Issue by marcinmaciukiewicz** [harrisoncramer/gitlab.nvim#142]
## Bug Description

I've self-hosted the repository on a docker. As a result, there is a special port to connect to the GitLab repository: port number 5022. 

The URL to clone the repository looks like this:

ssh://git@lab.xxx.yy:5022/project_group/project.git

My current authentication information are set like this:

```
auth_token=TOKEN
project_id=43
gitlab_url=https://lab.xxx.yy
```

When I'm trying to open the review I'm getting the error:

gitlab.nvim: 2023/12/15 05:47:22 Failed to initialize project settings: Error getting project at ssh://git@lab.xxx.yy:5022/project_group/project.git%!(EXTRA *gitlab.ErrorResponse=GET https://lab.xxx.yy/api/v4/projects/5022/project_group/
project: 404 {message: 404 Project Not Found})  

As you can see in the request, the plugin mixed the port from SSH (5022) as a part of the path to the project. If I clone the repo as https://..., everything works fine.

**Comment by harrisoncramer** [comment]
Hello, thank you for reporting this issue.

The regular expression that we use to parse the Git URL is in `git.go` -- you are welcome to modify it so that it works with PORTs, this is not a use-case that I'd seen before. Please see the `.github/CONTRIBUTING.md` for steps to run/test locally (we have a test file for this regular expression specifically).

**Comment by oartemios** [comment]
Hi! The same issue. Fixed locally via changing regexp in git.go and building gitlab.server after that, but it needs to be merged into master. Each update tries to rewrite this change. I would like to contribute into this issue

**Comment by harrisoncramer** [comment]
Sounds good, please make an merge request into the main branch, as described above, with the change and add a test case, and I'll merge your changes into the plugin.

**Comment by harrisoncramer** [comment]
Hey @oartemios @marcinmaciukiewicz would one of you be able to address this in an MR? I don't have a Gitlab server set up with a PORT so it'd be hard for me to fix this and verify it.

**Comment by oartemios** [comment]
Hi! Yes, I've made these changes in fork and it works. I have a branch that could be directed to original repo master. Will try  to create MR next week

**Comment by harrisoncramer** [comment]
As nobody has implemented this and there doesn't seem to be any activity on this issue, I'm going to close it. If you'd like to implement it please open up a merge request.
