### ISSUE TITLE
Use diffview.nvim "--imply-local" parameter, allowing for LSP use in merge reviews

### ISSUE THREAD

**Issue by d-karl** [harrisoncramer/gitlab.nvim#156]
## Feature Description
Hello, I am very excited about this plugin for the fact that I figured this would allow me to use LSP and the provided code intelligence on merge requests for review.

Diffview allows this via the --imply-local" parameter to `DiffViewOpen` command (see [diffview doc](https://github.com/sindrets/diffview.nvim/blob/main/doc/diffview.txt#L148)), and I found it easy to "hack into" this plugins sources. From what I am seeing it works well.

My question is would there be broader interest in this feature, and if so would you prefer to have an explicit gitlab.nvim option to use this one parameter, or would it maybe even be preferred to allow passing "any" parameter to `DiffViewOpen`, similar to how diffview.nvim does this through its `default_args` configuration (see [diffview doc](https://github.com/sindrets/diffview.nvim/blob/main/doc/diffview.txt#L670))?

**Comment by harrisoncramer** [comment]
Yes, this does seem very promising. I'd imagine that we could provide a configurable table via the setup call which would just be passed along to diffview, via the API you mention. 

Would you be interested in implementing this?

**Comment by d-karl** [comment]
I would love to give this a go and give something back to the neovim community!

**Comment by d-karl** [comment]
I made some progress on this today, and it is fairly straight forward to do, but based on prior discussion on #127 I did find an issue which I am not sure how to deal with:

When opening a Diffview with --imply-local, this will indeed show the state of the files in the MR **as they are on disk**, not necessarily as they are proposed for merging. As I understood it from the other discussion, this is a situation you would rather avoid, and I think with good reason.

Unfortunately, it does not appear that "Diffview" itself has any elaborate logic to deal with the issue at this point. IMO this leaves us with the following options for the "gitlab review" use case we are after in this repo, if we would still like to go ahead on this:

1. Accept that this is the case, and put responsibility for having "clean" local files on the user, and add that fact to documentation.
2. Make it an option to "attempt to use --imply-local", which would mean that the Diffview option is only used if we are sure there are no uncommitted changes on disk to files involved in the MR, otherwise we could warn and open without the option active.

Making it a "best effort" option would mean doing a few more git commands, which I'd have to look up. Basically: we would have to check which files are involved in the MR and then make sure these files have no uncommitted changes locally.

Thoughts?

FYI this is what I came up with in my tinkering: https://github.com/d-karl/gitlab.nvim/commit/6b6a37fe3cb423028fc1644c1dca32df30b6e854

**Comment by harrisoncramer** [comment]
Ah, okay -- this was my misunderstanding of how the `--imply-local` command works, but it does seem pretty easy to fix.

As you mention, the `--imply-local` command breaks if you have made modifications to the files, but have not committed.

Since this would basically be a case of user-error, I'd propose we abort opening the reviewer pane with an error message that tells the user to either stash them, commit and push, or remove the "imply local" option from their configuration.

I don't really think it's necessary to do this for specific files unless you feel otherwise, I'd suggest the simpler option of just checking the status generally.  Fortunately, @johnybx has basically already done the work for this, specifically check out the `git status --short` command in his previous MR: https://github.com/harrisoncramer/gitlab.nvim/pull/127/files#diff-fb9e92b5eb238329329ad98dd82fb12cf10c65bf99045954d54400ecb90babbdR33-R39

Does this make sense?

**Comment by d-karl** [comment]
I had the same misunderstanding. Yeah that does make sense, and is what I also thought of as option 2. Make the option "attempt to use imply-local", and only actually do it when it is safe. I'll add this to the proposal.

**Comment by d-karl** [comment]
Right I made the changes, I propose we use "git status --short --untracked-files-no". This will exclude untracked files from the output. Since untracked files cannot possibly be part of the MR, this is IMO more lenient and has no side effects that I can see. Personally, even though it may be against best practices I do tend to have a few untracked files around when I'm working away and hopping around branches.

Allow me a day of test-running my branch tomorrow (https://github.com/d-karl/gitlab.nvim/commit/78d2a89a39a0a515a37ee90a71d34d946aeb7ff0 if you're curious), when I'm back interacting with gitlab. If all goes well, I will open a pull request in the evening 😄.

**Comment by harrisoncramer** [comment]
This has been merged into main and shipped, thank you @d-karl for your contribution!
