### ISSUE TITLE
Discussion tree can be loaded into incorrect window

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#165]
## Bug Description

While Discussions data is being loaded, switching windows (e.g., to the reviewer, or the Diffview file panel) makes `gitlab.nvim` load the data in the newly focused window, not in the Discussions panel.

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Start a review
4. Run `gitlab.toggle_discussions`
5. Press `<C-W><C-W>` while "Loading data..." is being displayed in the Discussions panel
6. Wait for the discussion tree to be loaded into the focused window

**Comment by harrisoncramer** [comment]
Fixed by #167
