### ISSUE TITLE
Feature: Allow access to viewed feature?

### ISSUE THREAD

**Issue by briandipalma** [harrisoncramer/gitlab.nvim#166]
## Feature Description

No idea if the REST API allows this but if possible it might be good to allow marking files as viewed like you can via the web GUI:

![image](https://github.com/harrisoncramer/gitlab.nvim/assets/1597820/218e5ab4-b984-491f-8cb6-51b2d06eaf36)

**Comment by harrisoncramer** [comment]
This is a good idea but it's some state we'd have to manage locally.

Looking at Gitlab's site, it seems like they're storing this data in the user's browser in Local Storage, at the following key:

```
`/{org}/{project_name}/-/merge_requests/{merge_request_id_number}-file-reviews`
```

And that object has some sort of data structure that retains information about the file.

 I'm guessing they store somehow the hash of the file itself, and then the commit that you're "reviewing" at the time you press "view file" or something like that. We'd have to replicate this functionality locally, they don't have an API for it.

**Comment by briandipalma** [comment]
Hmm, OK that's far more complicated than I thought it would be. It's a pity it's not covered by the API. I'd consider this a very low priority feature request.

**Comment by harrisoncramer** [comment]
I'm going to close this for now, but we can reopen if we want to replicate a "viewed" functionality in the future.
