### ISSUE TITLE
Empty lines are incorrectly removed from code suggestions in discussion tree

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#170]
## Bug Description

If I try to make this code suggestion:
````
```suggestion:-1+0
from unittest import mock

import pytest
```
````

it is shown like this in the discussion tree even if it is displayed correctly on Gitlab in the browser:
````
```suggestion:-1+0
from unittest import mock
import pytest
```
````

This makes it difficult to be sure what the actual suggestion contains.

I've ben able to fix it in a very naive way with the following patch, but I believe there will be a safer way to do this:
```diff
diff --git a/lua/gitlab/actions/discussions/tree.lua b/lua/gitlab/actions/discussions/tree.lua
index 458b9b4..5a57d1c 100644
--- a/lua/gitlab/actions/discussions/tree.lua
+++ b/lua/gitlab/actions/discussions/tree.lua
@@ -92,7 +92,9 @@ end
 ---@return NuiTree.Node[]
 local function build_note_body(note, resolve_info)
   local text_nodes = {}
+  note.body = note.body:gsub("\n\n", "\nEMPTY_LINE_PLACEHOLDER\n")
   for bodyLine in note.body:gmatch("[^\n]+") do
+    bodyLine = bodyLine:gsub("^EMPTY_LINE_PLACEHOLDER$", "")
     local line = attach_uuid(bodyLine)
     table.insert(
       text_nodes,
```

**Comment by jakubbortlik** [comment]
A more standard approach seems to be this (recommended on [StackOverflow](https://stackoverflow.com/a/19329565)):
```lua
function magiclines(s)
        if s:sub(-1)~="\n" then s=s.."\n" end
        return s:gmatch("(.-)\n")
end
```

**Comment by harrisoncramer** [comment]
That sounds good, good ol' Stackoverflow.

If you wanted to implement an MR I'll review -- there may be a few other places in the codebase where we're splitting content like this too.

**Comment by jakubbortlik** [comment]
Hi, I'll be glad to create a PR. I hope I'll be able to do so over the weekend.

**Comment by harrisoncramer** [comment]
Sorry things have been crazy at work, just approved and merged this. Thank you for the contribution!
