### ISSUE TITLE
Feature "Add and Remove Labels from an MR" breaks Gitlab Summary

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#171]
## Bug Description

I don't use the Gitlab Summary too often so I only noticed this today. `gitlab.nvim` is broken for me since `50e06ceff6224cc1a0cb56340ea07be9842b2b96` which added the Label functionality.

Now whenever I try to open the Summary, I get this error: "gitlab.nvim: Failed to parse JSON from /mr/label endpoint, got: '404 page not found'".

**Comment by harrisoncramer** [comment]
The `/mr/label` endpoint shouldn't be 404-ing if you have the latest version of the plugin and have compiled the Go server correctly. You probably have an old version of the Go server running that doesn't have this endpoint, please make sure you are on the latest verison of the plugin and rebuild the server with:

```lua
require("gitlab").build()
```

Additionally you make have to kill the old server if it's already running.

**Comment by harrisoncramer** [comment]
Sounds good, I'll look into doing that in the future, glad to know you are unblocked.
