### ISSUE TITLE
Enable search in discussions

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#172]
## Feature Description

I'd like to easily find text in discussions/notes. Currently, to find any previous thread, I usually have to toggle a couple of nodes and then use normal search `/`. This is fine if there are just a couple threads, but it gets really inconvenient in actual MRs with tens of threads.

Even if I can imagine an actual search functionality that would make it possible to also search in collapsed nodes, take me to the node with a match and expand it for me, a simple "expand_all_nodes" method would be sufficient to provide the basic functionality that I'm lacking.

Then it would of course make sense to have "collapse_all_nodes", to clean up the view. Actually, something like "**toggle**_all_nodes" would be best, to be able to only use one keybinding for both, but I'm not sure how the plugin would determine whether to expand or collapse nodes if some were collapsed and some expanded...

**Comment by jakubbortlik** [comment]
For now, I'm using this workaround for collapsing/expanding all nodes (I'm using `i` as my `toggle_node` mapping). It's good enough for the basic functionality (being able to search all nodes' texts), but it does not keep the cursor position. And it's `vimscript` :) I was not able to figure out how to run `lua vim.cmd.normal` on a specific line (and this seemed necessary because I had to iterate the lines from the end of the file to the beginning, since a simple `g/^/normal i` on closed nodes didn't work, as it changed the number of lines and the command only expanded the nodes that were within the original line range.

```vim
scriptencoding utf-8
let g:gitlab_nvim_nodes_expanded = 0
function! ExpandAllNodes()
    for i in range(line('$'), 1, -1)
        if match(getline(i), '^') > -1
            execute i . 'normal i'
        endif
    endfor
    let g:gitlab_nvim_nodes_expanded = 1
endfunction
nnoremap <silent> <buffer> <leader><tab> :silent call ExpandAllNodes()<cr>

function! CollapseAllNodes()
    g/^/normal i
    let g:gitlab_nvim_nodes_expanded = 0
endfunction
nnoremap <silent> <buffer> <leader><S-tab> :silent call CollapseAllNodes()<cr>

function! ToggleAllNodes()
    if g:gitlab_nvim_nodes_expanded
        silent call CollapseAllNodes()
    else
        silent call ExpandAllNodes()
    endif
endfunction
nnoremap <silent> <buffer> <tab> :silent call ToggleAllNodes()<cr>
```

**Comment by harrisoncramer** [comment]
I'm going to close this since normal `/` and `?` search will be supported fine once you merge in the expand/collapse MR.
