### ISSUE TITLE
Mark unresolved discussions differently according to user involvement

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#178]
## Feature Description

Currently only resolved and unresolved discussions are marked differently (`'✓'` and `'-'`, respectively). This is already useful for filtering out discussions that are no more relevant. However, some useful information is still hidden in the "unresolved" discussions. I think any of the following could be useful for easier identification of discussions that are important and deserve my attention:
- discussions where I am mentioned
- discussions where there is a reply to my comment
- discussions where I haven't yet participated
- discussions where the original poster (OP) is waiting for a reaction

These states could mean different things based on whether I'm the author of the MR and I'm looking for comments from others, or I'm reviewing someone else's MR, so I'd like to have a simple way to customize marking different states of discussions and possibly switching within the reviewing session, without having to modify my global configuration.

This is still a rough idea, I believe something like this would be useful, because now, if there are e.g., 35 unresolved discussions in a MR, I'm the OP in many of them, I've got no clue if any of them have been addressed by the MR author. If there was e.g., a `!` for a discussion with a reply from the author, I know immediately that I want to se it.

There could eventually be a way how to connect this functionality with #176 so that I could for instance expand and search all open threads where I'm involved and do similar things.

**Comment by harrisoncramer** [comment]
Hey thank you for the idea, however because it would require a good amount of new state management, and is not a part of Gitlab currently, it's not something that I'm going to add to this plugin (anytime soon). 

For now the goal of this plugin is to achieve near-feature parity with what can be done in the browser, rather than implementing additional functionality.
