### ISSUE TITLE
Show emoji reactions to discussion nodes

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#179]
## Feature Description
If the Gitlab API makes the emoji reactions available, it would be useful to show them in `gitlab.nvim`. Not that I am particularly crazy about emojis, but I've just had a case where in a thread I asked for approval of a code change and a colleague replied only with a :ok_hand: on my discussion node. Currently, in `gitlab.nvim` I would miss this information and wouldn't proceed with the intended code change.

**Comment by harrisoncramer** [comment]
Implemented by #181
