### ISSUE TITLE
Improve discussion node toggling

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#185]
## Bug Description

The toggling of all/resolved/unresolved nodes does not work correctly in (at least) the following cases:
1. When discussions are toggled on (expanded), and a discussion is created/deleted/edited or the whole discussions split is toggled off and on again, the keybinding for toggling needs to be pressed twice
    - This should be easy to fix by resetting the state of toggling to `false` in `rebuild_discussion_tree` and `rebuild_unlinked_discussion_tree`.
2. There is just one set of states for the resolved and unresolved discussions, but there are two trees: discussions and notes.
    - There should be two separate sets of states for individual trees. Probably instead of a plain `state.resolved_expanded` there could be `state.discussion_tree.resolved_expanded` and `state.unlinked_discussion_tree.resolved_expanded`.

@harrisoncramer, can I just open a PR with a fix?

**Comment by harrisoncramer** [comment]
Yeah for sure, sounds good 👍

**Comment by jakubbortlik** [comment]
So the pull request is ready.

I've got two other ideas for small improvements in the discussion trees, but I'd rather do them in a separate PR:
- make it possible to toggle individual nodes (`"t"` keymap) even from the "note body" without having to move to the "note" node first
- make it possible to `toggle_resolved` also from note bodies and child nodes - currently, the cursor must be on the root node for toggling to work

@harrisoncramer, are you OK with both additions?

**Comment by harrisoncramer** [comment]
Yeah those seem like fine additions, I'd review them if you put them in another MR. Taking a look at the first PR now.
