### ISSUE TITLE
2FA login failing?

### ISSUE THREAD

**Issue by briandipalma** [harrisoncramer/gitlab.nvim#187]
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin

## Bug Description

I can't start a review any longer

## Reproduction Steps

Our admins recently changed some settings in our GL repo and I think along with the fact we now have 2FA enabled the URLs that used to work to request project info now fail.

```
Error  10:47:20 notify.error gitlab.nvim: 2024/02/19 10:47:20 Failed to initialize project settings: 
Error getting project at https://USER_NAME:AUTH_TOKEN@gitlab.COMPANY.com/front-end/mono.git%!
(EXTRA *gitlab.ErrorResponse=
GET https://gitlab.COMPANY.com//api/v4/projects/AUTH_TOKEN@gitlab.COMPANY.com/front-end/mono: 
404 {message: 404 Project Not Found})
```

When I browse to `https://gitlab.COMPANY.com/api/v4/projects/front-end%2Fmono` I get the expected JSON payload, as I'm logged in and the browser uses my cookies. In an incognito tab it fails and I can't formulate a URL that lets me access the JSON payload even when I add my username and auth token in the URL. I can get it to work with curl when I run:

```
curl --header "PRIVATE-TOKEN: AUTH_TOKEN" "https://gitlab.COMPANY.com/api/v4/projects/front-end%2Fmono"
```

The projects visibility is "internal", maybe before it was "public"? Does gitlab.nvim use the headers to send the auth token? I don't think encoding them in the URL works in all circumstances.

**Comment by harrisoncramer** [comment]
This plugin hands off all interactions with Gitlab to the [Go Gitlab](https://github.com/xanzy/go-gitlab) library. The authentication token is handled by that library as well. Can you please see if you are able to get a response using the instructions from this minimal repository: https://github.com/harrisoncramer/gitlab.nvim-troubleshooting

If not, then it's not an issue with this plugin but something to do with your specific GitLab instance and possibly this library.

**Comment by harrisoncramer** [comment]
Hey @briandipalma were you able to try the above and did you get an error? I'd like to help but am not sure what might be going wrong -- my company also uses two factor authentication and I do not have this issue.

**Comment by briandipalma** [comment]
I just tried it and it works fine.

```
⬢ [env:latest] ❯ ./gitlab-binary 22 https://COMPANY.caplin.com AUTH_TOKEN                                                                at 17:45:10
[gitlab.MergeRequest{ID:38714,
 IID:9924, 
TargetBranch:"master",
 SourceBranch:"FXST-7996-duplicate-margin-ticket",
 ProjectID:22,
 ...]⏎  
```

It must be the URL that it's using is wrong. 

```
⬢ [env:latest] ❯ g remote get-url origin                                                                                               took 2m31s at 17:51:38
https://USER_NAME:AUTH_TOKEN@gitlab.COMPANY.com/front-end/mono.git
```

How is that wrong?

This URL fails:

```
https://gitlab.COMPANY.com//api/v4/projects/AUTH_TOKEN@gitlab.COMPANY.com/front-end/mono
```

Maybe we need to enable some setting to allow using the AUTH_TOKEN in the URL? Maybe the only way it works is using it in the header like curl does?

**Comment by briandipalma** [comment]
I'll dig into the code Friday and see what I can do, no idea what it's like. If it's feasible to provide a header or not.

**Comment by harrisoncramer** [comment]
Your URL above seems to have an extra slash after the URL, not sure if it's the same issue as here: https://github.com/harrisoncramer/gitlab.nvim/issues/189#issue-2147258588

It's got nothing to do with headers, that's not how this plugin or the library it relies on works.

**Comment by briandipalma** [comment]
It's not the trailing slash sadly, also

```
debug = { go_request = true, go_response = true },
```

doesn't seem to have helped. I see no extra messages in noice all message history. Is the log somewhere else?

**Comment by harrisoncramer** [comment]
```lua
      log_path = vim.fn.stdpath("cache") .. "/gitlab.nvim.log", -- Log path for the Go server
```

To get this filename:

```
:lua=(vim.fn.stdpath("cache") .. "/gitlab.nvim.log")
```

**Comment by briandipalma** [comment]
OK it was the origin URL I was using. It worked for any git operations but the decoding logic inside gitlab.nvim didn't strip out the auth token so I moved to a simple https remote URL and a credentials helper for git operations and that fixed the issue. It went from:

```
-- REQUEST --
GET /api/v4/projects/AUTH_TOKEN@gitlab%2ECOMPANY%2Ecom%2Ffront-end%2Fmono HTTP/1.1
Host: gitlab.COMPANY.com
Accept: application/json
Private-Token: REDACTED
User-Agent: go-gitlab
```

to 

```
-- REQUEST --
GET /api/v4/projects/front-end%2Fmono HTTP/1.1
Host: gitlab.COMPANY.com
Accept: application/json
Private-Token: REDACTED
User-Agent: go-gitlab
```

and it loads up again. I guess the URL parsing logic breaks on a colon as it stripped `https://USER_NAME:` from the URL but left `AUTH_TOKEN@gitlab.COMPANY.com/` which caused the issue. Anyway I'm fine using a credentials provider so I'll close this.

Wish I could use my SSH key again, so much easier.
