### ISSUE TITLE
Single-line comment creation fails for added lines in old version

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#193]
## Bug Description

Single-line comment creation fails in the following case. Let's say I have a `file.txt` which in the old version reads:

```
abc
```
In the new version that I'm trying to merge in it changes to:
```
abc
new
```
I try to add a comment on line "abc" in the OLD version and I get this error:
`gitlab.nvim: Could not create discussion: POST https://............/merge_requests/8/discussions: 400 {message: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}}`
## Other Details
The problem is that in the `get_modification_type` function in `lua/gitlab/reviewer/diffview.lua:342`, additions are only considered for the "new" window (to be more concrete, if `is_current_sha` is `true` and it is `true` if `current_win == b_win`).

**Comment by harrisoncramer** [comment]
Fixed by #202, will ship to main the next time develop merges.
