### ISSUE TITLE
Creating comments fails after going to another tab and back

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#195]
## Bug Description

When creating a new comment, if I switch tabs (e.g., with `gt` to see some context of what I'm commenting on), then I get back to the tab with the unfinished comment and try to apply it with `perform_action`, I get the following error: `gitlab.nvim: Could not create discussion: POST https://..................../merge_requests/8/discussions: 400 {message: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}}`

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Start a review
4. Run `lua require("gitlab").create_comment()`
5. Press `gt` to go the next tab (repeat until you get to the tab with the comment popup
6. Optionally: Type some text into the comment
7. Press the `settings.popup.perform_action` keybinding

**Comment by jakubbortlik** [comment]
I see you cannot replicate this. I've tried with this minimal init:
```lua
local root = vim.fn.stdpath("run") .. "/nvim/mininit"
vim.fn.mkdir(root, "p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "harrisoncramer/gitlab.nvim",
    dependencies = {
      "MunifTanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
      "sindrets/diffview.nvim",
      "stevearc/dressing.nvim",     -- Recommended but not required. Better UI for pickers.
      "nvim-tree/nvim-web-devicons" -- Recommended but not required. Icons in discussion tree.
    },
    enabled = true,
    build = function() require("gitlab.server").build(true) end, -- Builds the Go binary
    config = function()
      require("gitlab").setup()
      local gitlab = require("gitlab")
      vim.keymap.set("n", "glr", gitlab.review)
      vim.keymap.set("n", "gls", gitlab.summary)
      vim.keymap.set("n", "glA", gitlab.approve)
      vim.keymap.set("n", "glR", gitlab.revoke)
      vim.keymap.set("n", "glc", gitlab.create_comment)
      vim.keymap.set("v", "glc", gitlab.create_multiline_comment)
      vim.keymap.set("v", "glC", gitlab.create_comment_suggestion)
      vim.keymap.set("n", "glO", gitlab.create_mr)
      vim.keymap.set("n", "glm", gitlab.move_to_discussion_tree_from_diagnostic)
      vim.keymap.set("n", "gln", gitlab.create_note)
      vim.keymap.set("n", "gld", gitlab.toggle_discussions)
      vim.keymap.set("n", "glaa", gitlab.add_assignee)
      vim.keymap.set("n", "glad", gitlab.delete_assignee)
      vim.keymap.set("n", "glla", gitlab.add_label)
      vim.keymap.set("n", "glld", gitlab.delete_label)
      vim.keymap.set("n", "glra", gitlab.add_reviewer)
      vim.keymap.set("n", "glrd", gitlab.delete_reviewer)
      vim.keymap.set("n", "glp", gitlab.pipeline)
      vim.keymap.set("n", "glo", gitlab.open_in_browser)
      vim.keymap.set("n", "glM", gitlab.merge)
    end,
  }
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```
And I can reliably reproduce it in a specific case - the line I'm trying to comment on is the first line in the buffer, e.g., the file in the target branch looks like this:
```
abc
def
ghi
```
In the feature branch it looks like this:
```
abc
def
ghi
jkl
```
When I place the cursor on ine `abc` in any of the versions, run `lua require("gitlab").create_comment()`, I write a comment, then press `gt` twice and then `<leader>s` to apply the comment, then I get the error.

One more detail, maybe it helps debugging, after the error the cursor is placed in the `DiffView` file panel, or on the second line (`def`) in the "old" version window, if the file panel is hidden.

**Comment by harrisoncramer** [comment]
Fixed in the above branch. I'll merge this into develop now. The problem was that upon returning to the reviewer from another tab, Diffview does not send you to the previous window by default.
