### ISSUE TITLE
Feat: Edit the Description

### ISSUE THREAD

**Issue by harrisoncramer** [harrisoncramer/gitlab.nvim#20]
Pretty straightforward, I'm planning to introduce the ability to edit the description for an MR from within the editor. Right now you can view a summary with `:lua require("gitlab").summary()` but you cannot edit it.

**I am willing to submit a PR for this change**
- [x] yes
- [ ] no

**Comment by harrisoncramer** [comment]
If you pull down, does that fix things? I wasn't using the pre-initialized client, so the base URL was wrong.

**Comment by mnbroatch** [comment]
yep, perfect!
