### ISSUE TITLE
Alpha Status and Future Development

### ISSUE THREAD

**Issue by harrisoncramer** [harrisoncramer/gitlab.nvim#21]
## Breaking Changes:

This plugin is still under active development and breaking changes might be common. I'll do my best to indicate in commit messages that a change is breaking via conventional commit messaging. There are likely to be more breaking changes in the future as the plugin gets more stable.

## Seeking Contributions:

I'm essentially building out features that I'd find useful in my day job.

However, I'm looking for contributions from the Gitlab and Neovim communities. The nature of this plugin means that there are likely to be bugs that I won't catch, due to the way that various Gitlab repositories can be configured differently, API requests can fail for a variety of reasons, people have different workflows, and so forth. If you have experience with Lua, Go, and/or Gitlab's APIs, I'm more than happy to help take MRs into this project.

**Comment by mnbroatch** [comment]
Loving this so far! Question: what does base_branch do? It seems as long as I put a branch that exists, functionality is the same.

**Comment by harrisoncramer** [comment]
It's basically used to block the server from running. 

When you have your base branch set it won't try to start up the server and look for merge requests; there's no other way for the plugin to know when you're on a feature branch or not and it'll error because it'd try to look for a merge request by that branch name when none exists.

<img width="1017" alt="Screenshot 2023-08-14 at 8 47 07 PM" src="https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/ea4934b7-a6f2-48f1-b16a-ae492d055fc8">

**Comment by mnbroatch** [comment]
Ah, does the gitlab MR API just error if you query against the base branch? fair enough.

**Comment by harrisoncramer** [comment]
@mnbroatch After giving it some thought, I can just delay the attempt to startup the Go server until after you try to run the first command! 

This solves a bunch of issues at once and makes this setting irrelevant, see this PR which I'm merging right now https://github.com/harrisoncramer/gitlab.nvim/pull/40

**Comment by mnbroatch** [comment]
That's a good idea. Making an API call every time vim starts is pretty overkill. The error state might be confusing, because behavior will be inconsistent still depending on whether they're on the main branch or not but I imagine some error handling polish can be added in the future to address that, this is a definite improvement

**Comment by harrisoncramer** [comment]
I've mitigated that somewhat with a check for "main" or "master" in the Go code, so that folks are warned that they can't run it on non-feature branches. Otherwise it'll say that it can't find an MR for "X" branch if it can't find a feature branch with the API call. But yeah, happy to take MRs if you have more ideas 😆

**Comment by mnbroatch** [comment]
Definitely wouldn't hurt to dip my toe into another language or two... no promises :P
