### ISSUE TITLE
bug: attempt to index field 'cur_file' (a nil value)

### ISSUE THREAD

**Issue by ElricleNecro** [harrisoncramer/gitlab.nvim#217]
## Prerequsities

- [ x ] I'm on the latest version of the plugin
- [ x ] I've installed the required dependencies
- [ x ] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

```lua
return 	{
		"harrisoncramer/gitlab.nvim",
		dependencies = {
			"MunifTanjim/nui.nvim",
			"nvim-lua/plenary.nvim",
			"sindrets/diffview.nvim",
			-- "stevearc/dressing.nvim", -- Recommended but not required. Better UI for pickers.
			"nvim-tree/nvim-web-devicons" -- Recommended but not required. Icons in discussion tree.
		},
		enabled = true,
		-- tag = "v2.0.3",
		build = function () require("gitlab.server").build(true) end, -- Builds the Go binary
		config = function()
			require("gitlab").setup()
			-- print(require("gitlab").print_settings())
			-- require("gitlab.server").start(function() print("Server started") end)

			vim.keymap.set("n", "<leader>gr", require("gitlab").review, {silent=true, desc="Opening reviewer pane."})
		end,
	}
```

## Bug Description

When calling `lua require("gitlab").review()`, I get the following error:
```terminal
Error: gitlab.nvim: Error setting diagnostics: ...share/nvim/lazy/gitlab.nvim/lua/gitlab/reviewer/init.lua:220: attempt to index field 'cur_file' (a nil value)
```
Following, all the buffers opened by the command are empty.

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim on one of the modified files
3. run `lua require("gitlab").review()`

## Screenshots

![bug_gitlab nvim](https://github.com/harrisoncramer/gitlab.nvim/assets/3876671/d086ecd7-791b-4114-87df-2258feab9622)

**Comment by ElricleNecro** [comment]
It seems to be caused by `diff_refs.base_sha` and `diff_refs.head_sha` being identical, but I don't know why (I didn't find where they are defined right now).

**Comment by jakubbortlik** [comment]
Hi, ElricleNecro, I'm not sure if it's related to your problem, but why is there `Changes (0)` in the `DiffviewFilePanel` in your screenshot? Maybe you are getting this error because your MR is somehow irregular. I'm surprised you can even have a MR without any changes. When I try to do this, I'm getting the expected warning `gitlab.nvim: Merge request contains no changes` and the review does not even start. What kind of changes are there in your feature branch?

**Comment by ElricleNecro** [comment]
I realised a few minutes ago I was not reviewing the correct branch. Sorry for the issue. I did found another problem, but it may just be another problem on my side.

Thanks.
