### ISSUE TITLE
allow Squash and RemoveSourceBranch in CreateMrRequest

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#222]
## Feature Description

Currently it's possible to squash commits and request the source branch to be removed when _accepting_ a MR. I'd like to be able to specify these options already when _creating_ a MR, so that I don't have to go to the website to do this.

**Comment by jakubbortlik** [comment]
Hi @harrisoncramer It seems that adding the parameters should be fairly straightforward. I'll be glad to submit a PR if you agree.

**Comment by harrisoncramer** [comment]
Yes, this would be a nice addition. Currently we do not support this at time of merging (glM) or creating (glO) an MR, or make it visible to the user in the MR summary. I'd be open to an MR that implements this. Might be worth considering adding settings that would allow the user to specify default behaviors for this as well.
