### ISSUE TITLE
Allow insecure HTTPS connection to gitlab

### ISSUE THREAD

**Issue by tcordel** [harrisoncramer/gitlab.nvim#228]
## Feature Description

Thank's for the work done on the plugin. Unfortunately, i can't use it on my enterprise environment due to the bad certificate of the self hosted gitlab server.

Once trying to connect, it throws: 
```log
gitlab.nvim: 2024/03/28 15:06:21 Failed to initialize project settings: Error getting project at https://srv-git/esv2/eai.git%!(EXTRA *url.Error=Get "https://srv-git/api/v4/projects/esv2%2Feai": x509: certificate signed by unknown authority)
``` 

This request is about to add a configuration to allow an insecure connection to the gitlab server (ie, like --insecure option for curl command)

Thanks !

**Comment by harrisoncramer** [comment]
Hey, could you please try this branch, rebuild the server, and see if it works for you?

https://github.com/harrisoncramer/gitlab.nvim/pull/229

**Comment by tcordel** [comment]
Hi !

It works as expected ! Nice !
This plugin looks awesome,

Thanks dude,

**Comment by harrisoncramer** [comment]
I'll merge this into develop now. It'll be there for a few days while I make sure it doesn't cause other connectivity issues and then will merge into main.
