### ISSUE TITLE
Ability to fetch gitlab info (e.g. pipeline status)

### ISSUE THREAD

**Issue by agscala** [harrisoncramer/gitlab.nvim#231]
## Feature Description

I'd like to be able to integrate the pipeline status into my lualine config, but there doesn't seem to be any way to simply return the data.  

It would be great if there was an API to give me information about the current MR for use programmatically.

**Comment by harrisoncramer** [comment]
Hello @agscala I've created an MR (see above) that will allow you to query the underlying data behind this plugin. This includes the pipeline data that is used to build the pipeline popup, the currently authenticated user, etc.

The data you're looking for will be available in the response data under `data.info.pipeline` and can be accessed like this:

```lua
require("gitlab").data({ resources = {}, refresh = false }, function (data) 
    vim.print(data.info.pipeline) 
end)
```

If you'd like more data please see the `gitlab.data()` function definition under the help documentation. Please check out this branch of the plugin and let me know how it works for you?

**Comment by harrisoncramer** [comment]
I've gotten this working for my own Lualine, which I also use, it works like this. In my own personal configuration I have some helpers to tell whether I'm in a Gitlab project and whether I'm looking at a feature branch:

```lua
M.get_branch_name = function()
  local is_git_branch = io.popen("git rev-parse --is-inside-work-tree 2>/dev/null"):read("*a")
  if is_git_branch == "true\n" then
    for line in io.popen("git branch 2>/dev/null"):lines() do
      local current_branch = line:match("%* (.+)$")
      if current_branch then
        return current_branch
      end
    end
  end
end

M.is_gitlab_project = function()
  for line in io.popen("git remote get-url origin"):lines() do
    return string.find(line, "@gitlab") ~= nil
  end
  return false
end

M.is_gitlab_mr = function()
  local branch_name = M.get_branch_name()
  if not branch_name or branch_name == "main" or branch_name == "master" then
    return false
  end

  return M.is_gitlab_project()
end
```

Then the (simplified) version of my Lualine configuration looks like this:

```lua
local mrInfo = ""
local gitlabMr = function()
  if not require("git-helpers").is_gitlab_mr() then
    return ""
  end
  require("gitlab").data({ resources = {}, refresh = false }, function(data)
    mrInfo = string.format("  '%s' by %s", data.info.title, data.info.author.username)
  end)
  return mrInfo
end

return {
  'nvim-lualine/lualine.nvim',
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  config = function()
    require("lualine").setup({
      sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = { gitlabMr },
      },
    })
  end
}
```
