### ISSUE TITLE
Open file

### ISSUE THREAD

**Issue by droopy4096** [harrisoncramer/gitlab.nvim#233]
## Feature Description

when in GitLab review screen and any of the changed files is selected it would be nice to either be able to open current file for writing, either as a separate operation, or allow editing in-line.

**Comment by harrisoncramer** [comment]
I'm not sure what you mean by this 🤔 

Can you please elaborate... Do you just mean jumping to the same file locally?

**Comment by droopy4096** [comment]
> Do you just mean jumping to the same file locally?

yes. I'm trying to find parity between VSCode `gitlab` plugin and this plugin and I've got accustomed to using "open target file" or sometimes being able to modify file right within the diff itself.

**Comment by harrisoncramer** [comment]
The review pages are all handled by [diffview](https://github.com/sindrets/diffview.nvim) which this plugin is built on top of, see: `:h diffview-actions-goto_file_edit` for instance. I've got this mapped to `<CR>` so that if I'm in the reviewer I can press enter to go to the file locally.
