### ISSUE TITLE
Comment creation failing when local target branch does not exist

### ISSUE THREAD

**Issue by aravind2612krishna** [harrisoncramer/gitlab.nvim#247]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [ ] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

Standard

## Bug Description

When creating a diff with `imply_local` true, it fails in `git diff`. I'm working around with the below fix, (not able to submit PR due to some auth issues)
``` 
diff --git a/lua/gitlab/hunks/init.lua b/lua/gitlab/hunks/init.lua
index f90d6f1..1a41f83 100644
--- a/lua/gitlab/hunks/init.lua
+++ b/lua/gitlab/hunks/init.lua
@@ -101,7 +101,7 @@ local parse_hunks_and_diff = function(file_path, base_branch)
 
   local diff_job = Job:new({
     command = "git",
-    args = { "diff", "--minimal", "--unified=0", "--no-color", base_branch, "--", file_path },
+    args = { "diff", "--minimal", "--unified=0", "--no-color", "origin/" .. base_branch, "--", file_path },
     on_exit = function(j, return_code)
       if return_code == 0 then
         all_diff_output = j:result()
```

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Post a comment when target branch is not there in your local branches

**Comment by harrisoncramer** [comment]
Hey, the `--imply-local` attempts to use the local files on your system (hence the name --imply-local) but it could make sense to check whether the branch exists during that check and abort if it does not. Does that sound like something you'd be interested in submitting a PR for?

It would likely involve adding a command to `lua/gitlab/git.lua` and also a check and early return to the `M.open()` command under `lua/gitlab/reviewer/init.lua` if the user is using an `--imply-local` option, telling them to pull their origin. Not too hard!

**Comment by jakubbortlik** [comment]
There is a somewhat similar issue that a MR can be created even if the local frature branch does not exist on remote. Running `gitlab.review` or `gitlab.summary` then causes the "MR cintains no changes" error. Instead, the MR creation should be aborted and a message should be shown like when you try to push a local branch without a tracking remote. I was planning to do this, so I could sort out the missing local target branch in one PR.

**Comment by aravind2612krishna** [comment]
I'll still humbly try to argue that it is good to support the _target_ branch being remote in the MR, as the reason I'd use `--imply-local` is chiefly to make use of editor navigation features which don't usually work when the buffer has the remote file loaded. I think this is closer in spirit to [diffview.nvim](https://github.com/sindrets/diffview.nvim/blob/3dc498c9777fe79156f3d32dddd483b8b3dbd95f/USAGE.md?plain=1#L20)'s definition of it.

**Comment by harrisoncramer** [comment]
I'm open to whatever you want to implement, this isn't an issue I've had before. Feel free to open a PR.
