### ISSUE TITLE
Position and Size Properties in setup don't do anything

### ISSUE THREAD

**Issue by mnbroatch** [harrisoncramer/gitlab.nvim#26]
**Describe the bug**
Position and Size Properties in setup don't do anything

**To Reproduce**

1. Use the setup snippet in the readme
2. Change "20%" to "50%" under keymaps -> discussion_tree
3. Change "position" to "bottom" in the same object

**Expected behavior**
The list_discussions method should open a bottom split with 50% height. Instead, it still opens a 20% left split.

**Screenshots**

**Desktop (please complete the following information):**
macos

**Comment by harrisoncramer** [comment]
Should be fixed with that merge, if you update. Please let me know if that doesn't work.
