### ISSUE TITLE
Add command(s) to refresh discussions

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#267]
## Feature Description

I'd like to have a command (and ideally also a keybinding) for refreshing the discussion tree. Currently, if I want to refresh the tree, I have to toggle it twice, which is not practical - first of all, why run a command twice, if it could be just one command. But also, sometimes I modify the layout (make the vertically split discussion tree wider, etc.) and this change is lost when toggling. I'd just like to refresh the data.

I think the default keybinding for this inside the discussion tree could be `CTRL-R` as it is otherwise unused in the non-modifiable buffer. Alternatively, there could be a command that would work from anywhere in `nvim` and that users could map to whatever they liked, just like the other commands, e.g., `vim.keymap.set("n", "gl<c-r>", gitlab.refresh_discussions)`.

I can create a PR for this.

**Comment by jakubbortlik** [comment]
What I'd actually like to achieve is that the **nodes would not collapse** when refreshing the discussion tree and when adding or editing nodes. I've tried for some time to get this behaviour, but cannot figure it out. Interestingly, for deleting and adding replies, the tree behaves just the way I like - the toggling status of the tree is not changed. But when editing/adding nodes, the tree is completely rebuilt. I assume this has to do with the Go library and the Gitlab API, right? I'm afraid I wouldn't easily find a way how to get this done.

**Comment by harrisoncramer** [comment]
This will be addressed when #288 ships 🥳
