### ISSUE TITLE
error when no discussions exist for MR

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#274]
## Prerequsities

- [x] I'm on the latest version of the plugin: develop f604c9441fea7dc3d73719d2d1b87a502068cb0a
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

```lua
{
  "harrisoncramer/gitlab.nvim",
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
  },
  build = function()
    require("gitlab.server").build()
  end,
  dir = "~/path/to/my/cloned/version",
  config = function()
    require("gitlab").setup({})
  end,
}
```

## Bug Description

The split for discussions cannot be created when there are no discussions/notes.

## Reproduction Steps

1. Check out the feature branch for which no discussions exist in the MR
2. Open Neovim
3. Run `:lua require("gitlab").review()`
4. You will get the following error:
```
gitlab.nvim: No discussions, notes, or draft notes for this MR
Error executing vim.schedule lua callback: ...b/projects/feat4/lua/gitlab/actions/discussions/init.lua:117: attempt to index field 'split' (a nil value)
stack traceback:
        ...b/projects/feat4/lua/gitlab/actions/discussions/init.lua:117: in function 'cb'
        /home/jakub/projects/feat4/lua/gitlab/async.lua:26: in function 'fetch'
        /home/jakub/projects/feat4/lua/gitlab/async.lua:42: in function 'callback'
        /home/jakub/projects/feat4/lua/gitlab/job.lua:40: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by harrisoncramer** [comment]
Fixed in develop by #273, if not let me know here with another comment
