### ISSUE TITLE
Line breaks are removed from comments

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#282]
## Prerequsities

- [x] I'm on the latest version of the plugin: develop (fa16905fab17f5f655f959d469a22d0ef5cbf91b)
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Bug Description

New lines are removed from the text of a comment/note - in `Neovim` the line breaks are correct:
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/17056143/1a37cc34-8974-423b-ab74-779902afa2cb)

Whereas in Gitlab online, all the lines are concatenated:
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/17056143/16d9c204-d8cb-4dc3-b147-9144d52d63bd)

Two consecutive new lines are retained, though:
![image](https://github.com/harrisoncramer/gitlab.nvim/assets/17056143/4e2fd0ab-57a9-4b87-b274-c440c08b5cab)

**Comment by harrisoncramer** [comment]
This is strange, I'm actually able to replicate this with cURL like this:

```
$ curl -X PUT -H "PRIVATE-TOKEN: $GITLAB_TOKEN" -H "Content-Type: application/json" -d '{"note":"This is a multiline\nComment with\nSome line breaks","position":{"base_sha":"","head_sha":"","start_sha":"","position_type":"text"}}' https://gitlab.com/api/v4/projects/YOUR_PROJECT_ID/merge_requests/YOUR_MERGE_ID/draft_notes/DRAFT_NOTE_ID
```

It seems that a single `\n` character is not respected in their APIs?

**Comment by harrisoncramer** [comment]
Further confirming this is actually a Gitlab bug, you can see this if you toggle between rich text and regular editing for a comment with the exact same text: 

https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/1aaad832-2a8d-464d-9447-8972695fbd67

**Comment by jakubbortlik** [comment]
Oh my, I just realized, this is not a bug but normal markdown behaviour 🤦
