### ISSUE TITLE
Draft comment on empty file disappears without error upon publishing

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#283]
## Prerequsities

- [x] I'm on the latest version of the plugin - develop `fa16905fab17f5f655f959d469a22d0ef5cbf91b`
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Bug Description

It is possible to create a draft comment on an empty line (e.g., in the "OLD" window for a file that has been added, or in the "NEW" window for a file that has been deleted). The draft appears in the discussion tree but when it is published, it disappears without any error message.

In comparison, when publishing a normal ("non-draft") comment on an empty line, the correct error message is shown: `400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}`.

It would be nice it creating comments on empty lines was aborted early, without even opening the comment popup (maybe `gitlab.nvim` could support creating "file" comments (those without line information).

In any case, at least an error message should be shown when publishing drafts on empty lines.

**Comment by harrisoncramer** [comment]
Why are you trying to add a comment to an empty buffer?

**Comment by jakubbortlik** [comment]
Now that you ask, I realize it does seem like an odd thing to do. I was just experimenting with the draft feature and trying out all sorts of things. When a "file" comment is created online on a deleted file, it is actually shown in the empty "NEW" buffer. So there is a small chance that somebody will encounter such a comment and will think that it's possible to do the same in `gitlab.nvim`. But I guess you can ignore this issue as the probability that someone will actually do this is quite small.

**Comment by harrisoncramer** [comment]
No worries, appreciate your thoroughness. Probably good to check for user error. How about this: https://github.com/harrisoncramer/gitlab.nvim/pull/284

**Comment by harrisoncramer** [comment]
Fixed by #284
