### ISSUE TITLE
Parent comment deleted instead of child reply

### ISSUE THREAD

**Issue by mnbroatch** [harrisoncramer/gitlab.nvim#29]
**Describe the bug**
Deleting a reply to a comment actually deletes the parent comment above it, leaving the reply!

**To Reproduce**
1. Make a comment
2. Open the discussion list
3. reply to the comment
4. delete the reply

**Expected behavior**

I expect the discussion list to reflect the deleted reply

Instead, nothing is updated in the discussion list immediately, but looking in the gitlab ui or re-opening the discussion list, you can see the parent comment is deleted, INSTEAD of the reply! The reply is still there.

**Screenshots**

**Desktop (please complete the following information):**

**Comment by harrisoncramer** [comment]
Should be fixed by that merge, if it's not let me know and I'll reopen this issue.

**Comment by mnbroatch** [comment]
Looking good!
