### ISSUE TITLE
how to create merge reqeust from remote origin to remote upstream

### ISSUE THREAD

**Issue by jjpark78** [harrisoncramer/gitlab.nvim#301]
we are using git with fork based workflow. 

using this plugin how can i make a merge request from "forked" origin remote repository to upstream ?

thanks for your great work.

**Comment by harrisoncramer** [comment]
Hello,

This plugin currently assumes the feature branch and base branch are in the same repository (in this case `origin`) and the ability to add cross-remote logic would be a net-new feature.

**Comment by harrisoncramer** [comment]
Hello @jjpark78 can you please try the branch and tell me whether this implements the functionality you want? You should:

1. Check out the feature branch above
2. Rebuild the Go server (either run `make compile` in the plugin source or `:lua require("gitlab.server").build()`
3. Try to create an MR into a forked source

This is working for me!

**Comment by harrisoncramer** [comment]
This has been merged into main.
