### ISSUE TITLE
Discussion's `jump to file` hotkey leads to the location in the current codabase

### ISSUE THREAD

**Issue by shchemelevev** [harrisoncramer/gitlab.nvim#304]
## Prerequsities

- [x ] I'm on the latest version of the plugin
- [x ] I've installed the required dependencies
- [ x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

Since the comment is related to the specific commit `jump to file` has to lead to the code from that commit.
If the actual number of the line related to the comment has been changed or the line content has been changed, then it will be really difficult to understand the meaning of the comment.
This issue breaks the expected workflow and makes this feature unusable in a great number of cases.

**Comment by harrisoncramer** [comment]
Are you looking for the `jump_to_reviewer` action? That jumps to the comment in the reviewer window. The default keybinding for it is `m` not `o` which jumps to the buffer locally.

**Comment by shchemelevev** [comment]
Yes, I was looking for `jump_to_reviewer`. That is a bit confusing name for the hotkey, because there are API methods `add_reviewer` and `delete_reviewer`. In my mind it was connected to a person somehow, so I didn't notice the hotkey binding at all.

Also, when I try to `jump_to_reviewer` it says `Can't jump to Diffvew. Is it open?`.
