### ISSUE TITLE
Get error 'field 'DISCUSSION_DATA' is nil' when post comment

### ISSUE THREAD

**Issue by sergey-arkhipov** [harrisoncramer/gitlab.nvim#306]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run :h gitlab.nvim.troubleshooting and followed the steps there

## Setup Configuration and Environment

```lua
        discussion_tree = { -- The discussion tree that holds all comments
          auto_open = false, -- Automatically open when the reviewer is opened
...
``` 
## Bug Description
Got error
```shell
Error executing vim.schedule lua callback: ...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:59: attempt to index field 'DISCUSSION_DATA' (a nil value)
stack traceback:
  ...lazy/gitlab.nvim/lua/gitlab/actions/discussions/init.lua:59: in function 'cb'
  .../.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/state.lua:404: in function 'callback'
  ...as/.local/share/nvim/lazy/gitlab.nvim/lua/gitlab/job.lua:40: in function ''
  vim/_editor.lua: in function ''
  vim/_editor.lua: in function <vim/_editor.lua:0>

``` 

## Reproduction Steps

1. Set auto_open = false for discussion_tree in config
2. Open review mode
3. Make comment and save

## Screenshots

![Screenshot 2024-06-02 at 23 08 59](https://github.com/harrisoncramer/gitlab.nvim/assets/5460458/89336fc9-fca1-4297-9c91-e530129aaae0)

**Comment by harrisoncramer** [comment]
Thanks for filing this issue! It's fixed on main now.
