### ISSUE TITLE
Sporadically invalid highlight colors

### ISSUE THREAD

**Issue by FarbzeN** [harrisoncramer/gitlab.nvim#307]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

I implemented the plugin as follows:
```
return {
	"harrisoncramer/gitlab.nvim",
	dependencies = {
		"MunifTanjim/nui.nvim",
		"nvim-lua/plenary.nvim",
		"sindrets/diffview.nvim",
		"stevearc/dressing.nvim", -- Recommended but not required. Better UI for pickers.
		"nvim-tree/nvim-web-devicons", -- Recommended but not required. Icons in discussion tree.
	},
	enabled = true,
	build = function()
		require("gitlab.server").build(true)
	end, -- Builds the Go binary
	config = function()
    local gitlab = require("gitlab")
    gitlab.setup()
		vim.keymap.set("n", "<leader>glb", gitlab.choose_merge_request, { desc = "Choose merge request" })
		vim.keymap.set("n", "<leader>glr", gitlab.review, { desc = "Review" })
		vim.keymap.set("n", "<leader>gls", gitlab.summary, { desc = "Summary" })
		vim.keymap.set("n", "<leader>glA", gitlab.approve, { desc = "Approve" })
		vim.keymap.set("n", "<leader>glR", gitlab.revoke, { desc = "Revoke" })
		vim.keymap.set("n", "<leader>glc", gitlab.create_comment, { desc = "Create comment" })
		vim.keymap.set("v", "<leader>glc", gitlab.create_multiline_comment, { desc = "Create multiline comment" })
		vim.keymap.set("v", "<leader>glC", gitlab.create_comment_suggestion, { desc = "Create comment suggestion" })
		vim.keymap.set("n", "<leader>glO", gitlab.create_mr, { desc = "Create merge request" })
		vim.keymap.set("n", "<leader>glm", gitlab.move_to_discussion_tree_from_diagnostic, { desc = "Move to discussion tree" })
		vim.keymap.set("n", "<leader>gln", gitlab.create_note, { desc = "Create note" })
		vim.keymap.set("n", "<leader>gld", gitlab.toggle_discussions, { desc = "Toggle discussions" })
		vim.keymap.set("n", "<leader>glaa", gitlab.add_assignee, { desc = "Add assignee" })
		vim.keymap.set("n", "<leader>glad", gitlab.delete_assignee, { desc = "Delete assignee" })
		vim.keymap.set("n", "<leader>glla", gitlab.add_label, { desc = "Add label" })
		vim.keymap.set("n", "<leader>glld", gitlab.delete_label, { desc = "Delete label" })
		vim.keymap.set("n", "<leader>glra", gitlab.add_reviewer, { desc = "Add reviewer" })
		vim.keymap.set("n", "<leader>glrd", gitlab.delete_reviewer, { desc = "Delete reviewer" })
		vim.keymap.set("n", "<leader>glp", gitlab.pipeline, { desc = "Pipeline" })
		vim.keymap.set("n", "<leader>glo", gitlab.open_in_browser, { desc = "Open in browser" })
		vim.keymap.set("n", "<leader>glM", gitlab.merge, { desc = "Merge" })
		vim.keymap.set("n", "<leader>glu", gitlab.copy_mr_url, { desc = "Copy MR URL" })
		vim.keymap.set("n", "<leader>glP", gitlab.publish_all_drafts, { desc = "Publish all drafts" })
		vim.keymap.set("n", "<leader>glD", gitlab.toggle_draft_mode, { desc = "Toggle draft mode" })
	end,
}
```

## Bug Description

When opening neovim with `gitlab.nvim` enabled, I sporadically get the following error:
```
Failed to run `config` for gitlab.nvim

....local/share/nvim/lazy/gitlab.nvim/lua/gitlab/colors.lua:10: Invalid highlight color: '14'

# stacktrace:
  - /gitlab.nvim/lua/gitlab/colors.lua:10
  - /gitlab.nvim/lua/gitlab/init.lua:38 _in_ **setup**
  - ~/.config/nvim/lua/plugins/gitlab.lua:16 _in_ **config**
  - ~/dotfiles/nvim/init.lua:17
 ```

Afterwards, I need to restart neovim a few times until the error does not appear.

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim

**Comment by harrisoncramer** [comment]
Interesting, this appears to be an issue with looking up a local color highlighting for the `Directory` group. You can trigger this error manually in Neovim like this, because "14" is not a valid color:

```lua
vim.api.nvim_set_hl(0, "GitlabDate", { fg = '14' })
```

 Can you please try creating this file on your local system:

```lua
-- the-file.lua 
local group = "Directory"
local get_colors_for_group = function(group)
  local normal_fg = vim.fn.synIDattr(vim.fn.synIDtrans((vim.fn.hlID(group))), "fg")
  local normal_bg = vim.fn.synIDattr(vim.fn.synIDtrans((vim.fn.hlID(group))), "bg")
  return { fg = normal_fg, bg = normal_bg }
end

local results = get_colors_for_group(group)
vim.print(results)
```

And then running it with Neovim:

```bash
:so the-file.lua
```

What does it return for you? For me, it returns a Lua table that looks like this:

```lua
{
  bg = "",
  fg = "#7e9cd8"
}
```

Which is then used to color the directories in the discussion tree. It seems likely that for you it's returning an invalid table for some reason which is being fed into `lua/gitlab/colors.lua` which is then causing the issue.

**Comment by FarbzeN** [comment]
The file returns the following regardless of if there is an error on startup or not:
```lua
{
  bg = "",
  fg = "#7aa2f7"
}
```

However, if I place the code to run before 
```lua
local gitlab = require("gitlab")
gitlab.setup()
```

I sometimes get the following lua table which corresponds to my error message:
```lua
{
  bg = "",
  fg = "14"
}
```

**Comment by harrisoncramer** [comment]
This is tricky for me to debug for you since I'm not able to replicate it locally and it is not happening consistently. A few other things I'd recommend looking into:

1. Check that you have the Directory group set correctly: `:hi Directory` 
2. Try changing the setup call for the plugin to use a different color group for the one that's causing you issues:

```lua
    require("gitlab").setup({
      colors = {
        discussion_tree = {
          directory = "Normal", -- Use a different highlight group here, like "Normal" 
        }
      }
    })
```
You could also try removing/commenting out other plugins in batches to determine when/where the conflict is arising. It may be that another plugin or color scheme is setting that value incorrectly.

**Comment by FarbzeN** [comment]
I managed to figure out, that the inconsistent nature of this issue is a race condition between the plugin and my colorscheme being loaded.

If the colorscheme (`tokyonight`) is loaded first, everything is fine. Otherwise I get this error.
Disabling my colorscheme makes this error happen consistently.

`:hi Directory` without my colorscheme gives me the following output:
```lua
Directory      xxx ctermfg=14 guifg=NvimLightCyan
```

I also realized that this error only happens when I use nvim in a tmux session.
I run tmux with the following setting:
```conf
set-option -g default-terminal "screen-256color"
```

I appear to have found a workaround by adding my colorscheme to the dependencies of the plugin:
```lua
  dependencies = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim",
    "sindrets/diffview.nvim",
    "folke/tokyonight.nvim",
    "stevearc/dressing.nvim",    -- Recommended but not required. Better UI for pickers.
    "nvim-tree/nvim-web-devicons", -- Recommended but not required. Icons in discussion tree.
  },
```

**Comment by harrisoncramer** [comment]
Gotcha, I'm glad you were able to find a solution. 

This seems like a weird compatibility issue with Tmux, likely something in your settings there is causing this issue. I'm also a Tmux user and haven't been able to replicate it, but since you are unblocked I'll close this out.
