### ISSUE TITLE
Feat: Make Remote Configurable

### ISSUE THREAD

**Issue by lewisdiamond** [harrisoncramer/gitlab.nvim#314]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

N/A

## Bug Description

[Hard coded `origin`](https://github.com/search?q=repo%3Aharrisoncramer%2Fgitlab.nvim%20origin&type=code)

While some people may use the gitlab instance as the origin remote, there can be multiple remotes and can be named anything, not just `origin`. The remote needs to be found from the configured gitlab url by matching with the list of remotes. 

## Reproduction Steps

N/A

**Comment by tboehler1** [comment]
While this isn't implemented it would be great if there was a note in the documentation and especially the README of the project about origin being hard coded.

**Comment by jakubbortlik** [comment]
I've added a note about "origin" in #320, so it's now in branch "develop", but maybe it should be in "main" as that is probably what most people are using. So depending on whether/when @harrisoncramer plans to implement this feature (#314) it could make sense to also merge #320 to "main" for now.

**Comment by harrisoncramer** [comment]
I marked this as a good first issue, since the change would be straightforward to add (adding a setting to the configuration function and then passing it as a parameter to the Go server), and I'd like to encourage others to implement new features that they want; I'm not opposed to adding it at all.

**Comment by harrisoncramer** [comment]
@lewisdiamond or @tboehler1 I've implemented this in https://github.com/harrisoncramer/gitlab.nvim/pull/348

Does this branch work for you?
