### ISSUE TITLE
question: how to post a comment

### ISSUE THREAD

**Issue by jordankoehn** [harrisoncramer/gitlab.nvim#322]
I set this up today and it looks amazing. MRs on gitlab have a terrible diff view

Anyway, dumb question. I can get into the comment buffer with `glc` and type it out, but I can't seem to figure out how to submit it

Thanks

**Comment by harrisoncramer** [comment]
https://github.com/harrisoncramer/gitlab.nvim/blob/3c9d95d25b75d1942de9bdfa85dea113a9307e18/doc/gitlab.nvim.txt#L175

Thanks for the kind words. This is the primary action keybinding, by default `<leader>s`
