### ISSUE TITLE
Closing the discussion tree takes too long

### ISSUE THREAD

**Issue by briandipalma** [harrisoncramer/gitlab.nvim#326]
## Prerequsities

- [X] I'm on the latest version of the plugin
- [X] I've installed the required dependencies
- [X] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

```lua
function()
		local config = {
			config_path = "/home/brian/dev/my-data/",
			attachment_dir = "/home/brian/Pictures/Screenshots",
			reviewer_settings = {
				diffview = {
					imply_local = true,
				},
			},
			popup = {
				perform_action = "<leader>ms",
				perform_linewise_action = "<leader>ml",
				width = "80%",
				comment = { opacity = 0.8 },
				temp_registers = { "+" },
			},
			discussion_tree = { position = "bottom" },
			discussion_sign_and_diagnostic = {
				skip_resolved_discussion = true,
			},
		}

		require("gitlab").setup(config)
	end
```

## Bug Description

Closing the discussion tree takes far longer than it should, I guess there is some async call to the GL server going on before it closes the window?

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Close any discussion tree, they all seem to take ages

**Comment by harrisoncramer** [comment]
Hey Brian,

Thanks for the report. You can check out [this branch](https://github.com/harrisoncramer/gitlab.nvim/pull/328) which should improve some of the slowness (we were making API calls on close _and_ open by accident).

You may also check that whatever keybinding you're using for opening the discussion tree is not a prefix to another keybinding, which could be causing this. For instance, you can run `:map gld` to see if that's the case.

```
:map gld
n  gld         * <Lua 472: ~/.config/nvim/dev-plugins/gitlab/lua/gitlab/init.lua:71>
```

**Comment by harrisoncramer** [comment]
This should now be fixed on main, closing but please feel free to leave another comment here if you're still having trouble.

**Comment by briandipalma** [comment]
Works great, thanks for the fix!
