### ISSUE TITLE
Cant install on Windows 

### ISSUE THREAD

**Issue by Umzugskarton** [harrisoncramer/gitlab.nvim#34]
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies

## Bug Description

When I PackerSync I only get the Message 'Could not install gitlab.nvim'.
at one point there is another error wich says : "C:\PathToPacker\gitlab.nvim/bin' is not recognized as an internal or external command,^M" 
notice the different slashes.
I am on a windows machine perhaps thats the issue? 

## Reproduction Steps

1. Add use 'harrisoncramer/gitlab.nvim' to config file
2. :PackerSync

**Comment by Umzugskarton** [comment]
I perhaps got a fix , but I somehow cant push a Branch - perhaps its restricted , would have loved to contribute to the project.

**Comment by harrisoncramer** [comment]
@Umzugskarton Hey were you still planning to work on this, or did you want an assist?

I could probably spin up a windows machine on AWS if you aren't able to commit some time to this, but I'd like to get Windows support soon if possible. Thanks again for raising this issue!
