### ISSUE TITLE
`E382: Cannot write, 'buftype' option is not set.` can't proceed creating a new MR.

### ISSUE THREAD

**Issue by stefanoamorelli** [harrisoncramer/gitlab.nvim#343]
## Prerequisites

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

I'm using `LazyVim`:

```lua
return {
	{
		"harrisoncramer/gitlab.nvim",
		dependencies = {
			"MunifTanjim/nui.nvim",
			"nvim-lua/plenary.nvim",
			"sindrets/diffview.nvim",
			"stevearc/dressing.nvim", -- Recommended but not required. Better UI for pickers.
			"nvim-tree/nvim-web-devicons", -- Recommended but not required. Icons in discussion tree.
		},
		enabled = true,
		build = function()
			require("gitlab.server").build(true)
		end, -- Builds the Go binary
		config = function()
			local gitlab = require("gitlab")
			gitlab.setup()
			vim.keymap.set("n", "glO", gitlab.create_mr)
		end,
	},
}
```

## Bug Description

I receive the `E382: Cannot write, 'buftype' option is not set.` error when trying to save a new MR title and description from the popup triggered by `gitlab.create_mr`

## Reproduction Steps

1. Press `glO` in normal mode;
2. Fill the MR title and description (note that I have to switch to insert mode by pressing `i`);
3. Write `:wq` to proceed with the creation of the MR;
4. I get `E382: Cannot write, 'buftype' option is not set.`  and can't proceed with creating the MR.

---

Any help is greatly appreciated!

**Comment by harrisoncramer** [comment]
Hey @stefanoamorelli,

These buffers are not writeable like normal buffers, in order to actually finalize the description and send the content to Gitlab, use the `perform_action` keybinding. By default this is `<leader>s` but after this MR is merged it'll be `ZZ`

Does that help?

**Comment by stefanoamorelli** [comment]
Thanks a lot @harrisoncramer, that solves the issue!
