### ISSUE TITLE
Resolve/Unresolve discussions on MR

### ISSUE THREAD

**Issue by mnbroatch** [harrisoncramer/gitlab.nvim#36]
## Feature Description

Should be able to mark discussions resolved / unresolved

**Comment by harrisoncramer** [comment]
This is a good idea. How do you think we should surface this information in the discussion tree? I'm thinking perhaps an emoji next to each item, like this:

![image](https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/27b5ff3f-2b74-47ba-a9dd-9842ad0bcb4d)

The emoji would be configurable.

**Comment by harrisoncramer** [comment]
Yes the content is configurable, and could be set for either resolved or unresolved comments. It'd be any valid UTF-8 text that Neovim can display. 

I've got an MR that implements the PATCH calls, just have to add some logic for updating the tree nodes. Should have it done in a day or two.

**Comment by harrisoncramer** [comment]
This is now implemented in the linked branch. 

Would you please verify that it works for you by using that branch of the plugin? This can be done with Lazy by specifying the branch of a repository, in this case it'd be the `resolve-unresolve-discussions` branch I'd think.

**Comment by mnbroatch** [comment]
Yep, looks good to me!
