### ISSUE TITLE
Time when MR was closed or merged is shown in bad format

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#363]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Bug Description

This code in `lua/gitlab/reviewer/init.lua:69`
```lua
  if state.INFO.state == "closed" then
    u.notify(string.format("This MR was closed on %s", u.format_date(state.INFO.closed_at)), vim.log.levels.WARN)
  end

  if state.INFO.state == "merged" then
    u.notify(string.format("This MR was merged on %s", u.format_date(state.INFO.merged_at)), vim.log.levels.WARN)
  end
```

Produces output like `gitlab.nvim: This MR was merged on 24 minutes`. Maybe it should just show the date in the original format like `gitlab.nvim: This MR was merged on 2024-09-11T08:18:41.664Z`. I thinks it's informative and readable enough.

**Comment by harrisoncramer** [comment]
We have a `u.time_since` utility that we probably just want to use here, no?

**Comment by jakubbortlik** [comment]
Oh, yes, it didn't occur to me to look around in the code base. #367 fixes this.
