### ISSUE TITLE
Invalid Git URL Format

### ISSUE THREAD

**Issue by niderhoff** [harrisoncramer/gitlab.nvim#364]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

Please post here the options you're passing to configure `gitlab.nvim` and specify any environment variables you're relying on.

```
GITLAB_TOKEN=<REDACTED_TOKEN>                                                                                       
GITLAB_URL=https://<REDACTED_HOST>     
```

```lua
return {
    "harrisoncramer/gitlab.nvim",
    dependencies = {
        "MunifTanjim/nui.nvim",
        "nvim-lua/plenary.nvim",
        "sindrets/diffview.nvim",
        "stevearc/dressing.nvim",     -- Recommended but not required. Better UI for pickers.
        "nvim-tree/nvim-web-devicons" -- Recommended but not required. Icons in discussion tree.
    },
    enabled = true,
    build = function() require("gitlab.server").build(true) end, -- Builds the Go binary
    config = function()
        require("gitlab").setup({
            debug = {
                go_request = true,
                go_response = true,
            },
        })
    end,
}
```

## Bug Description

On every I get the following error:

`
gitlab.nvim: Failure initializing plugin: Invalid Git URL format: https://oauth2:<REDACTED_TOKEN>@https://<REDACTED_HOST>/<redacted group>/<redacted group>/<redacted-repo-name>/   
`

even when I try the trouble shooting step of 

```lua
require("gitlab.server").start(function() print("Server started") end)
```

The error is happening, so I expect the gitlab server is not even starting and I can't do any other trouble shooting steps.

When I change the remote url from the original format `https://oauth2:<redacted_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>/`

to `https://oauth2:<redacted_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>` I am able to start the server, but a `404` error happens.

I tried the following remote-urls:

- `https://oauth2:<redacted_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>/`    --> "Invalid Git URL Format"
- `https://oauth2:<redacted_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>.git/` --> "Invalid Git URL Format" 
- `https://oauth2:<redcated_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>`    --> "Error getting project at ... 404 Not Found"
- `https://oauth2:<redacted_token>@<redacted_host>/<redacted group>/<redacted group>/<redacted-repo-name>.git` --> "Error getting project at ... 404 Not Found"  
   
   However, through my browser all of them work.

## Reproduction Steps

1. set env variables
2. neovim plugin config
3. `git clone <git url>`
4. Open Neovim
5. lua require'gitlab'.choose_merge_request()  

## Screenshots

...

**Comment by harrisoncramer** [comment]
Hey @niderhoff, it looks like this might be easy to fix, we just don't have that `oauth2` prefix in our regular expression currently:

```go
	re := regexp.MustCompile(`(?:^https?:\/\/|^ssh:\/\/|^git@)(?:[^\/:]+)(?::\d+)?[\/:](.*)\/([^\/]+?)(?:\.git)?$`)
```

You can see where this change might need to be made in `cmd/app/git/git.go` and `cmd/app/git/git_test.go` would you like to try making an MR to fix it? If so, you can check out the contributing file at `.github/CONTRIBUTING.md`

I'd be happy to try and fix this for you but it'd be hard since I do not have this type of repository set up.

**Comment by niderhoff** [comment]
Thank you for accepting the PR. In fact this is my first time touching a Go project :)

**Comment by harrisoncramer** [comment]
NIce! Yeah Go is a great language. I'll close this issue but please drop a comment here if there's an issue still with the URL for you.
