### ISSUE TITLE
Use conceal functionality to show emojis (:thumbsup: -> 👍)

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#385]
## Feature Description
I think it would be quite nice to use the conceal functionality  in markdown buffers like the discussion tree and the comment composition buffers to _visually_ replace the text like `:thumbsup:` with the actual Unicode symbols like :+1:.

@harrisoncramer, do you think this is something you'd be willing to include in the plugin? I haven't checked whether there is another plugin that does this.

I'm only afraid that adding 570 or more syntax rules for each emoji such as `syntax match emoji_tada ":tada:" conceal cchar=🎉` could negatively affect responsiveness of the UI.

**Comment by harrisoncramer** [comment]
If we wanted to add something like this it'd probably be worth making opt-in. I'm not sure what the performance implications would be, you're welcome to give it a try and see. Other Gitlab integrations (like IntelliJ has one) don't do this

**Comment by jakubbortlik** [comment]
From the user perspective, this is basically just a cosmetic thing, so if you don't mind keeping the issue open foe some time, I'll get back to it after some more functional issues are sorted out. I've got a couple ideas about emojis, so I'll just list them here, but I can open separate issues, if you prefer.

1. Where does the list of emojis in `config/emojis.json` come from? Gitlab online seems to support quite a few more than `gitlab.nvim` does. I'll be adding those that come up in our team's discussions, but maybe I could try to find some more exhaustive list from Gitlab right away.
2. The emojis in `config/emojis.json` also include a `short_name` (the string that one would normally have to type literally in markdown for the emoji to show up on Gitlab) and an array of `keywords`. It would be great, if these were also used for fuzzy searching for an emoji.
3. It would be nice if the emojis could be autocompleted while working on markdown buffers, but I guess there are existing plugins for this, so it's probably superfluous for `gitlab.nvim` to implement this functionality.

**Comment by jakubbortlik** [comment]
> From the user perspective, this is basically just a cosmetic thing, so if you don't mind keeping the issue open foe some time, I'll get back to it after some more functional issues are sorted out. I've got a couple ideas about emojis, so I'll just list them here, but I can open separate issues, if you prefer.
> 
>     1. Where does the list of emojis in `config/emojis.json` come from? Gitlab online seems to support quite a few more than `gitlab.nvim` does. I'll be adding those that come up in our team's discussions, but maybe I could try to find some more exhaustive list from Gitlab right away.
> 
>     2. The emojis in `config/emojis.json` also include a `short_name` (the string that one would normally have to type literally in markdown for the emoji to show up on Gitlab) and an array of `keywords`. It would be great, if these were also used for fuzzy searching for an emoji.
> 
>     3. It would be nice if the emojis could be autocompleted while working on markdown buffers, but I guess there are existing plugins for this, so it's probably superfluous for `gitlab.nvim` to implement this functionality.

Regarding point 1, there's this massive list of round 890 emojis (I guess it probably already contains most of those in `gitlab.nvim`: https://gist.github.com/rxaviers/7360908.

**Comment by jakubbortlik** [comment]
I've made some progress in this. I'd like to make the list for the emoji picker configurable so users can show the `short_name` along with or instead of the `emoji` if they wish, e.g., if emojis are not rendered nicely in their UI, or they just want to search for the `moji.short_name` when they don't remember the text that is in the `moji.name` description. I hope I'll create a PR soon.

Regarding the conceal functionality, the problem is that both `syntax match... conceal ccha=CHAR` and `matchadd(..., {conceal = CHAR})` require `CHAR` to be a single character. However, many emojis are *not* a single character and so `syntax match AngelTone1 ":angel_tone1:" conceal cchar=👼🏻 ` fails with an error, and the corresponding `matchadd` call only takes the first character from `👼🏻 ` which removes the skin tone. With skin tones this is not a big issue, but with some other basic emojis in combination with the "Variation Selector-16" `FE0F`, like e.g., `261D`, up-pointing index, after the `FE0F` is removed, the base emoji `261D` can be rendered very badly (e.g., not shown at all) in some system configurations (e.g., many terminals with tmux running).

This could be solved in the future if [anticonceal](https://github.com/neovim/neovim/pull/9496) gets implemented and multiple characters could be used for concealing text. In the meantime, a workaround could be that a proper conceal is created for emojis that are just one character wide (`vim.fn.strchars(v.moji) == 1`), and for the composed emojis, we could just use some alternative highlighting or leave them alone completely.

@harrisoncramer what do you think? Maybe we can just leave the conceal functionality alone until it can be done properly for all emojis, rather than having this inconsistency which might confuse users.

**Comment by jakubbortlik** [comment]
After trying to implement the conceal feature for emojis, while I liked what it looked like, I've come to the conclusion that it is general markdown/emoji functionality and should not be part of `gitlab.nvim`.
