### ISSUE TITLE
Incorrect warning about local commits

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#387]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Bug Description

The warning message `You have local commits that are not on origin. Have you forgotten to push?` is shown incorrectly in at least the following cases:

- The MR has already been closed and the feature branch has been deleted - in this case the warning is completely misleading.
- The feature branch has been rebased on the remote - in this case the message could rather say "Have you forgotten to pull?".

The `gitlab.git.current_branch_up_to_date_on_remote` function should be changed so that it is more universal, ideally without making it slower by adding more `git` calls.

**Comment by harrisoncramer** [comment]
This is addressed here, please take a look: https://github.com/harrisoncramer/gitlab.nvim/pull/395
