### ISSUE TITLE
Plugin fails to build

### ISSUE THREAD

**Issue by kostya9** [harrisoncramer/gitlab.nvim#390]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment
```
return {
	"harrisoncramer/gitlab.nvim",
	dependencies = {
		"MunifTanjim/nui.nvim",
		"nvim-lua/plenary.nvim",
		"sindrets/diffview.nvim",
		"stevearc/dressing.nvim", -- Recommended but not required. Better UI for pickers.
		"nvim-tree/nvim-web-devicons" -- Recommended but not required. Icons in discussion tree.
	},
	enabled = true,
	build = function() require("gitlab.server").build(true) end, -- Builds the Go binary
	config = function()
		require("gitlab").setup({
			debug = {
				request=true,
				response=true,
				gitlab_request=true,
				gitlab_response=true,
			},
			log_path = "D:/gitlab.nvim.log"

		})
	end,
}
```
OS: Windows

## Bug Description

When installing the plugin, it does not build the server binary. At the same time, building manually via `go build -o bin.exe` works (running in gitlab.nvim/cmd directory).

My hypothesis: it tries to build the binary in the wrong directory.

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Observe error:
```
Could not install gitlab.nvim!
```
4. Observe that there is no binary bin.exe in gitlab.nvim folder.

## Screenshots

![image](https://github.com/user-attachments/assets/79a62097-b2f2-476b-a5e6-c6080faeb58b)

**Comment by harrisoncramer** [comment]
Interesting. I'm not a Windows user so this would be hard for me to debug, as you've already determined there's something going wrong here:

```lua
  local file_path = u.current_file_path()
  local parent_dir = vim.fn.fnamemodify(file_path, ":h:h:h:h")
  state.settings.bin_path = parent_dir
  state.settings.bin = parent_dir .. (u.is_windows() and "\\bin.exe" or "/bin")

  if not override then
    local binary_exists = vim.loop.fs_stat(state.settings.bin)
    if binary_exists ~= nil then
      return
    end
  end

  local cmd = u.is_windows() and "cd %s\\cmd && go build -o bin.exe && move bin.exe ..\\"
    or "cd %s/cmd && go build -o bin && mv bin ../bin"

  local command = string.format(cmd, state.settings.bin_path)
  local null = u.is_windows() and " >NUL" or " > /dev/null"
 
  -- If you add this line we can see the command that's actually being run
  print(command .. null)

  local installCode = os.execute(command .. null)
  if installCode ~= 0 then
    u.notify("Could not install gitlab.nvim!", vim.log.levels.ERROR)
    return false
  end
  u.notify("Gitlab.nvim installed successfully!", vim.log.levels.INFO)
  return true
```

To debug this, I'd probably want to know the exact command the plugin is trying to run. You can see that if you change into the plugin directory and edit that function in `lua/gitlab/server.lua` to add a print before the command is actually executed.

**Comment by harrisoncramer** [comment]
This is something to do with your setup.

With an EC2 instance running Windows and with the basic requirements needed for this plugin (Lazy, Neovim, Go, and the bare bones configuration from the Readme), the plugin installed the `bin.exe` in the correct location and everything worked as expected.

**Comment by harrisoncramer** [comment]
Hey @kostya9 are you able to provide the above information?

**Comment by kostya9** [comment]
Sorry for the long delay.

The command looks fine, but it fails for some reason. When I copy this command and run manually - it works. Now that I think about it - this may be connected to the fact that I use PowershellCore as terminal instead of the default things, and maybe my vim terminal settings are causing this issue.

![image](https://github.com/user-attachments/assets/53fbf699-9320-4051-ab1d-19e21c714d13)

**Comment by kostya9** [comment]
The build command starts to work if I change it to this (executing commands via vim.system):
```
![image](https://github.com/user-attachments/assets/9daf622a-1219-4e40-a42e-260d4b3b2645)
```

**Comment by harrisoncramer** [comment]
That's hugely helpful, thank you.

I've opened up an MR that should fix this: https://github.com/harrisoncramer/gitlab.nvim/pull/419

Do you mind checking out this branch and tell me if the server builds correctly? You should be able to check out a specific branch with Lazy, then run this to force a rebuild:

```
:lua require("gitlab.server").build(true)
```

**Comment by Daydreamer-riri** [comment]
Hi @harrisoncramer, How do I know if I built it correctly? 

I now get an error:
```
   Error  21:04:17 notify.error gitlab.nvim: panic: could not find emojis at ./config/emojis.json
goroutine 1 [running]:

   Error  21:04:17 notify.error gitlab.nvim: github.com/harrisoncramer/gitlab.nvim/cmd/app.CreateRouter(0xc000252000, 0x1?, 0xc00011fd88, {0xc00011fdf0, 0x3, 0x5c35a7?})
	D:/Users/ding.zhao/AppData/Local/nvim-data/lazy/gitlab.nvim/cmd/app/server.go:94 +0x3b4b
github.com/harrisoncramer/gitlab.nvim/cmd/app.StartServer(0xc000252000, 0xc00023a678, {{0xc000174ff0, 0x42}, {0xc000175010, 0xb}, {0xc00017501c, 0x12}, {0xc00023e000, 0x24}})
	D:/Users/ding.zhao/AppData/Local/nvim-data/lazy/gitlab.nvim/cmd/app/server.go:26 +0x156
main.main()
	D:/Users/ding.zhao/AppData/Local/nvim-data/lazy/gitlab.nvim/cmd/main.go:45 +0x397

   Error  21:04:17 notify.error gitlab.nvim: Golang gitlab server exited: job_id: 9, exit_code: 2

```

**Comment by harrisoncramer** [comment]
Ah, okay I think that was due to me using forward slashes in the emoji location, I've made this fix:

![Screenshot 2024-11-11 at 8 46 27 AM](https://github.com/user-attachments/assets/2f4c040d-67dc-425c-b14d-662d85b19191)

Could you pull down the latest for this branch and try again: https://github.com/harrisoncramer/gitlab.nvim/pull/419

**Comment by Daydreamer-riri** [comment]
Hi @harrisoncramer, I tried it out and it's running well. However, I encountered this issue: I can't close any of the `gitlab.nvim` pop-up windows using `esc` or `q`. Is this normal?

**Comment by harrisoncramer** [comment]
I'm not sure why your diagnostics wouldn't close. But both of these are separate issues from this original issue, if you are unable to resolve them please open up a separate ticket. I'll close this one out now.

**Comment by Daydreamer-riri** [comment]
Thank you so much for your support! This is a great plugin.

**Comment by kostya9** [comment]
Checked on my machine, it now works too, thanks!
