### ISSUE TITLE
Draft replies to comments are incorrectly shown as draft notes.

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#392]
## Bug Description

Draft replies to comments are incorrectly shown as draft notes. As can be seen in the screenshots below, there are two draft comments, one of them a reply to an existing comment. There is, however, no draft note, even it the winbar says otherwise:

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
3. Create a draft reply

## Screenshots
![image](https://github.com/user-attachments/assets/378e2087-8b13-40f6-9750-3f494a0b0d10)
![image](https://github.com/user-attachments/assets/7f5a1eff-24a3-463a-9e9c-53a58ae89f65)

**Comment by jakubbortlik** [comment]
@harrisoncramer I can fix this one if you haven't started working on it yet.

**Comment by harrisoncramer** [comment]
That'd be great, thank you!
