### ISSUE TITLE
Comment creation should not be possible for renamed and moved files

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#400]
## Bug Description
Gitlab currently does not support commenting on moved/renamed files ([see this issue for implementing that feature](https://gitlab.com/gitlab-org/gitlab/-/issues/371752)). `gitlab.nvim` should make it impossible for the user to even start creating an inline comment (or draft inline comment) on such files, as they currently inevitably end with an error (direct comments) or just get lost silently (drafts).

## Reproduction Steps

1. Check out the feature branch
2. `git mv file_name new_file_name && git add . && git commit -m 'rename file' && git push`
3. Open Neovim
4. Run `lua require("gitlab").review()`
5. Make a comment on the moved file -> Error `400 {message: 400 Bad request - Note {:line_code=>["can't be blank", "must be a valid line code"]}}`
6. Make a *draft* comment on the moved file. Then publish the draft -> No error, but draft does not show up in the discussion tree

**Comment by harrisoncramer** [comment]
There are some middleware functions that check the validity of the file before running certain operations. Maybe we should add to that function a check on\ whether a file is renamed. WDYT?

**Comment by jakubbortlik** [comment]
Yes, I think it would be good to warn users early, that the feature is not supported (yet), so they don't waste time on handling errors. It's questionable if the feature will ever be implemented since it is one among tens of thousands open issues on Gitlab.
