### ISSUE TITLE
Non-resolvable notes are not shown in winbar

### ISSUE THREAD

**Issue by jakubbortlik** [harrisoncramer/gitlab.nvim#411]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Bug Description

The winbar of the discussion tree is useful in showing the number of threads that need to be addressed. Currently, however, it doesn't show the number of non-resolvable notes (i.e., notes that are not a thread with the "Resolve" button). This makes it possible to miss such a note completely in `gitlab.nvim`

## Reproduction Steps

1. In Gitlab online create a "Comment" (not a Thread!), see screenshot below
2. Check out the feature branch
3. Open Neovim
4. If there are no other notes in the MR and the discussion tree is showing Inline comments, the winbar doesn't give you any hint that there are any Notes at all.

## Suggested fix

Add count of non-resolvable notes to the winbar, possibly also replace "resolved" with "threads" and swap the order of `resolvable/resolved` to `resolved/resolvable`, as it corresponds better to the way of saying "1 out of 5 are resolved". The final winbar text could look like this: `Notes (2 comments; 1/5 threads; 2 drafts)`.

## Screenshots

![image](https://github.com/user-attachments/assets/c9865714-68e1-43f6-a829-b69b2440336d)

**Comment by harrisoncramer** [comment]
Hey, thank you for filing this issue Jakub.

"Add count of non-resolvable notes to the winbar, possibly also replace "resolved" with "threads" and swap the order of resolvable/resolved to resolved/resolvable, as it corresponds better to the way of saying "1 out of 5 are resolved". The final winbar text could look like this: Notes (2 comments; 1/5 threads; 2 drafts)."

This sounds good to me ☝️  are you willing to submit a pull request for this?

**Comment by jakubbortlik** [comment]
Hi, Harrison, sure, I will submit a PR. First I'll finish some work in order to close #385 and then I'll fix the winbar in this issue.

**Comment by harrisoncramer** [comment]
Addressed by #417
