### ISSUE TITLE
Wrong get request URL

### ISSUE THREAD

**Issue by OscarCreator** [harrisoncramer/gitlab.nvim#412]
## Prerequsities

- [x] I'm on the latest version of the plugin
- [x] I've installed the required dependencies
- [x] I've run `:h gitlab.nvim.troubleshooting` and followed the steps there

## Setup Configuration and Environment

Default options with the debug options set to true

## Bug Description

I have a gitlab URL like https://a.b.com/git which seems to be wrongly used in get requests. The GET path becomes
```
/git/api/v4/projects/git%2Fproject-name
```
But it should be 

```
/git/api/v4/projects/project-name
```

## Reproduction Steps

1. Check out the feature branch
2. Open Neovim
4. Run `:lua require("gitlab").review()

**Comment by harrisoncramer** [comment]
Hey, thank you for filing an issue, the git files, which contain the pattern matching for URLs, are pretty well tested. Would you be wiling to submit a pull request for this issue?

**Comment by OscarCreator** [comment]
I think the problem may lay somewhere here https://github.com/harrisoncramer/gitlab.nvim/blob/main/cmd%2Fapp%2Fgit%2Fgit.go#L68
As it assumes that the first thing after the first / has to be a namespace but for me that isn't true. It should somehow trim the part of the URL which is written in the config file.

**Comment by harrisoncramer** [comment]
Thank you for your contribution!
