### ISSUE TITLE
Feature Request: Add functionality to mark a merge request as "Ready" directly from the plugin.

### ISSUE THREAD

**Issue by zaakiy** [harrisoncramer/gitlab.nvim#443]
## Expected Behavior

Users should be able to mark a merge request as "Ready" using `gitlab.nvim` without needing to switch to the GitLab web interface.

## Current Behavior

Currently, there is no functionality in `gitlab.nvim` to mark a merge request as "Ready." This must be done manually via the GitLab web interface.

## Possible Solution

Implement an option in the plugin's menu or command set that allows users to mark a merge request as "Ready." This could involve:
1. Adding a new command (e.g., `:GitlabMRReady`).
2. Making an API call to GitLab to update the merge request's state to "Ready."
3. Providing confirmation or feedback to the user after the action.

## What is the motivation / use case for changing this?

Improving the workflow for developers by enabling them to manage merge requests entirely within Neovim, saving time and reducing context switching.

## Sample API Payload

```json
{
    "operationName": "toggleDraftStatus",
    "variables": {
        "projectPath": "current/devops/terraform",
        "iid": "40",
        "draft": false
    },
    "query": "mutation toggleDraftStatus($projectPath: ID!, $iid: String!, $draft: Boolean!) {\n  mergeRequestSetDraft(\n    input: {projectPath: $projectPath, iid: $iid, draft: $draft}\n  ) {\n    mergeRequest {\n      id\n      mergeableDiscussionsState\n      title\n      draft\n      __typename\n    }\n    errors\n    __typename\n  }\n}\n"
}
``` 

## Steps

1. [ ] Provide a command to mark a merge request as "Ready", and to change it back to "Draft"
2. [ ] Ensure the command makes the appropriate API call and handles errors gracefully.
3. [ ] Display success or failure feedback to the user.
4. [ ] Create `gl`-based keyboard shortcut to easily toggle the merge request draft/ready status

**Comment by harrisoncramer** [comment]
My understanding is that Gitlab determines whether something is a draft (or is ready for review) based on the presence of "Draft:" in the title. You can see this if you add or remove "Draft:" from the front of your MR, it'll switch between ready and draft status.

So, what you are describing should already be possible by just editing the title of the MR. Does that work for you?

**Comment by zaakiy** [comment]
> My understanding is that Gitlab determines whether something is a draft (or is ready for review) based on the presence of "Draft:" in the title. You can see this if you add or remove "Draft:" from the front of your MR, it'll switch between ready and draft status.

Unfortunately that is not the correct method of using this feature. Let me make a video of it and show you; not sure if I can upload videos....

**Comment by zaakiy** [comment]
@harrisoncramer please find here the video I created to describe the need for this feature. 

https://youtu.be/a4EuuKw24-Q
(higher quality should be available ~20 mins after time of this comment)

It is a heavy part of our GitLab workflow, and without it this feature being integrated into your plugin, it means that I need to go to the web UI for GitLab.

I truly understand how valuable your time is, which is why I took the time to send you the sample API payload to help (in the original message above). Unfortunately, I've not got the skills to do this otherwise I would have loved to submit a pull request for this, given how important it is to me.

Thank you for your time and for your amazing plugin.

**Comment by harrisoncramer** [comment]
Hey Zaakiy, thank you for the video. After looking around a lot on Gitlab's API documentation, as far as I'm able to tell, there is not anything available to set an MR to "ready/draft" directly. This _is_ possible via the GraphQL API, but this plugin does not use GraphQL. 

When you are toggling that button, I'm still under the belief that what Gitlab is doing under the hood is modifying the title of your MR by adding "Draft" at the front, and then updating it's status. You can see in your video that the title of your MR is actually changing when you toggle that button. I've added two videos below showing that the two behaviors appear identical. 

Unfortunately, if this doesn't fit your use case, we won't be able to support updating the status anytime soon because we do not use GraphQL for this plugin.

https://github.com/user-attachments/assets/e2cb6443-b9ae-4bc0-8652-3b4d2c9c6049

https://github.com/user-attachments/assets/81240acd-66a8-4527-8ba6-b019b0dbe1b2

**Comment by zaakiy** [comment]
@harrisoncramer thank you! I made the mistake of thinking that this feature was more complicated than it actually is. Really appreciate you taking the time to clarify!

Believe it or not I actually came back here to tell you the same thing...I tested it out for myself, then came back here and saw your explanation and videos. So embarrassed to have wasted your time...thanks!

**Comment by harrisoncramer** [comment]
No worries at all!
