### ISSUE TITLE
Where should I place the .gitlab.nvim file?

### ISSUE THREAD

**Issue by whxcode** [harrisoncramer/gitlab.nvim#45]
"I attempted to place the .gitlab.nvim file under ~/.gitlab.nvim, and even after running the require("gitlab").summary() command, I still receive the error message 'The gitlab.nvim state was not set. Do you have a .gitlab.nvim file configured?'"

**Comment by harrisoncramer** [comment]
That file should be in the root of your project folder alongside your `.git` folder, not at ~/.gitlab.nvim

**Comment by whxcode** [comment]
> That file should be in the root of your project folder alongside your `.git` folder, not at ~/.gitlab.nvim

Thanks
