### ISSUE TITLE
Add comments to diagnostics and sighcolumn

### ISSUE THREAD

**Issue by mrparalon** [harrisoncramer/gitlab.nvim#47]
Usually it is handy to see other comments when you are reading throw code.

How I see the feature:
- I go throw code and see "C" in sighcolumn (could be toggled by command)
- I check diagnostic message and see thread
- I can reply it this thread using command

**Comment by johnybx** [comment]
If you want you  can test this [PR](https://github.com/harrisoncramer/gitlab.nvim/pull/78)

**Comment by harrisoncramer** [comment]
This has been merged, and is now supported, if you pull down the latest version of the plugin you'll have in-buffer diagnostics for different comments. If you notice issues with this feature or have other requests please open up another request or PR. Thank you both!
