### ISSUE TITLE
Populate quick fix list with comments

### ISSUE THREAD

**Issue by mrparalon** [harrisoncramer/gitlab.nvim#48]
It is a built in tool for lists. For example, I have keybindings for going throw a list. 

I think it will work good with https://github.com/harrisoncramer/gitlab.nvim/issues/47

**Comment by harrisoncramer** [comment]
Unfortunately due to the way the discussion tree works I don't think this one will be possible, at least without a lot of work. If you'd like to try implementing it you can go for it, but it's not high on my list of priorities.
