### ISSUE TITLE
Not open file from discussion pannel in a new tab

### ISSUE THREAD

**Issue by mrparalon** [harrisoncramer/gitlab.nvim#50]
Me and as I understand some other developers don't use tabs as it works in vscode.

Is it possible to add option to open file from discussion pannel in last active buffer for example?

**Comment by harrisoncramer** [comment]
I'd be happy to implement this but want to make sure I understand the request.

Do you mean that you'd like to move the cursor to the previous window (not buffer) in Neovim, and then open up the file in that window? This would look something like this:

https://github.com/harrisoncramer/gitlab.nvim/assets/32515581/0adefc6d-9feb-4c0c-8df0-7266ec962c82

I'm not sure what this has to do with VSCode, this is a Neovim plugin...

**Comment by harrisoncramer** [comment]
Please try the branch listed above and let me know if this is the functionality you were hoping for.

**Comment by mrparalon** [comment]
Yes, video looks good, that what I meant

I tried branch, now it opens file in discussion window, but not in a window I jumped to discussions
