### ISSUE TITLE
Diffview reviewer does not work

### ISSUE THREAD

**Issue by gunslingerfry** [harrisoncramer/gitlab.nvim#71]
## Prerequsities

- [X] The "Troubleshooting" section of the README did not help
- [X] I've installed the required dependencies
- [X] I'm on the latest version of the plugin

## Bug Description

Using diffview as the pager does not work. This might be an initialization order problem.

## Reproduction Steps

1. Add the packer use command as shown in the readme adding the reviewer option
```lua
use {
  'harrisoncramer/gitlab.nvim',
  requires = {
    "MunifTanjim/nui.nvim",
    "nvim-lua/plenary.nvim"
  },
  run = function() require("gitlab.server").build(true) end,
  config = function()
    require("gitlab").setup({reviewer="diffview})
  end,
}
```
2. Install diffview
```lua
use {
      'sindrets/diffview.nvim',
      config=function() require('diffview').setup() end
  }
```
3. Open Neovim

Receive error message: `packer.nvim: Error running config for gitlab.nvim: .../pack/packer/start/gitlab.nvim/lua/gitlab/utils/init.lua:17: Please install diffview or change your reviewer`

Again, I'm not sure if this is an initialization order problem on my end or what. The use command for the diffview plugin is before the gitlab plugin. Diffview works as expected from within vim. 

edit: So it looks like the check that is failing is the `vim.fn.exists(":DiffviewOpen")` in utils.lua. I don't know when that is supposed to become available but it is true that that check fails. However removing the check in utils.lua allows me to use diffview with gitlab.

**Comment by harrisoncramer** [comment]
Interesting, thank you. I'll look into this now.

**Comment by harrisoncramer** [comment]
Hello again, I've merged in a change that should fix this (see the above MR). Please let me know if this resolves your issue?

**Comment by gunslingerfry** [comment]
Yes! Thank you!
