### ISSUE TITLE
Search up the file hierarchy to find the .gitlab.nvim file

### ISSUE THREAD

**Issue by gunslingerfry** [harrisoncramer/gitlab.nvim#76]
## Feature Description

If you open vim within a subfolder in a repo and do `:lua require("gitlab").review() ` you get the (very helpful) error message: "The gitlab.nvim state was not set. Do you have a .gitlab.nvim file configured?" Instead, the plugin should search up the repo hierarchy to find the .gitlab.nvim file.

**Comment by harrisoncramer** [comment]
Hey @gunslingerfry the `.gitlab.nvim` file is now optional, and the only required environment variable (unless you're in a private/self-hosted repo) is the auth token.

Does this get around this issue for you?
