### ISSUE TITLE
Are forward slashes `/` in branch names supported?

### ISSUE THREAD

**Issue by bfulop** [harrisoncramer/gitlab.nvim#79]
## Prerequsities

- [x] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin
- [x] I've checked out the feature branches

## Bug Description

I've tried gitlab.nvim on two repos. In one of the repos it seems to work well, I can open and navigate the changed files ✔︎

In the second one however, I get this message:

```
[Diffview.nvim] Failed to parse rev "feature/TI-29320@"!
Git output:
Press ENTER or type command to continue |
```

Besides the fact this second repo is much much bigger, it looks to me the only difference between them is the "folder organisation" of the git branches: the branches names contain one or more `/` forward slashes.

Do you think it could be the reason?

**Comment by johnybx** [comment]
:wave: hmm, the message looks like it originate directly from [diffview.nvim](https://github.com/sindrets/diffview.nvim/blob/d38c1b5266850f77f75e006bcc26213684e1e141/lua/diffview/vcs/adapters/git/init.lua#L1334-L1345) but I am not able to reproduce it :thinking:. I tested with these branches:
```
  feature/TI-29320@
  with-slash-and-at/QA-123@
  with-slash/QA-123
```
and everything seems to work.

**Comment by bfulop** [comment]
Thanks for the verifying on your side! I figured out what was causing my issue:

The MR I tried to review did not target the `main` branch but some other, temporary one. You need to have checked out both the source and target to be able to create the diff. This is what diffview was complaining about (same issue with delta).
