### ISSUE TITLE
Connect to self hosted Gitlab instances

### ISSUE THREAD

**Issue by lukastillmann** [harrisoncramer/gitlab.nvim#8]
**Describe the solution you'd like**
This is an amazing plugin. I would love to be able to use this with self hosted Gitlab instances

**I am willing to submit a PR for this change**
- [ ] yes
- [x] not at the moment

**Comment by aap01** [comment]
Great plugin! 
It would have been my daily driver if self-hosted gitlab instances supported

**Comment by Otterpatsch** [comment]
Would also be very interested. How can one help?

**Comment by Otterpatsch** [comment]
@harrisoncramer I noticed a fork of this repo https://github.com/marcinmaciukiewicz/gitlab.nvim has the desired feature? Would love to use the your repo nonetheless over a fork

**Comment by Otterpatsch** [comment]
@harrisoncramer sadly i dont but im happy to test and give any bug reports as soon as one can use it in any way with self hosted instances

**Comment by Otterpatsch** [comment]
How can setup the self host within the self hsot branch? Let where to set the custom gitlab host?

**Comment by harrisoncramer** [comment]
This is now supported, please see my comment here on how to configure a self-hosted instance: https://github.com/harrisoncramer/gitlab.nvim/pull/10
