### ISSUE TITLE
Diffview Doesn't Load correctly with Packer

### ISSUE THREAD

**Issue by teto** [harrisoncramer/gitlab.nvim#94]
## Prerequsities

- [ ] The "Troubleshooting" section of the README did not help
- [x] I've installed the required dependencies
- [x] I'm on the latest version of the plugin

## Bug Description
In lua/gitlab/reviewer/diffview.lua there is a `local diffview_lib = require("diffview.lib")` line that triggers 

```
|| ...ck/home-manager/start/diffview.nvim/lua/diffview/lib.lua:12: attempt to index global 'DiffviewGlobal' (a nil value)
|| # stacktrace:
||   - ~/.local/share/nvim/site/pack/home-manager/start/diffview.nvim/lua/diffview/lib.lua:12
||   - /gitlab.nvim/lua/gitlab/reviewer/diffview.lua:5
||   - /gitlab.nvim/lua/gitlab/reviewer/init.lua:2
||   - /gitlab.nvim/lua/gitlab/init.lua:5
||   - ~/.config/nvim/lua/lazyplugins/git.lua:10 _in_ **config**
||   - ~/.config/nvim/lua/init-manual.lua:60
||   - ~/home/config/nvim/init.lua:12
```
if you have https://github.com/sindrets/diffview.nvim installed as well aka  `require("gitlab.diffview.lib")` instead. 

everything included should be scoped by the plugin name. 

## Reproduction Steps

install https://github.com/sindrets/diffview.nvim and gitlab.nvim

**Comment by harrisoncramer** [comment]
Hey Teto, thanks for reporting this.

Yes, this is why for Packer and Lazy `diffview` is listed in the `dependencies` or `requires` section of the plugin configuration. Are you still stuck or did you get this resolved?

**Comment by teto** [comment]
I think it's ok. Depending on how I launch neovim I see some errors like an highlight missing for gitlab.nvim but it's not a big problem. Let's close

**Comment by thomasgrz** [comment]
Thank you so much for this plugin!

Just FWIW, I'm running into the same error:

```
packer.nvim: Error running config for gitlab.nvim: ...ite/pack/packer/start/diffview.nvim/lua/diffview/lib.lua:12: attempt to index global 'DiffviewGlobal' (a
 nil value)
```

I've actually tried deleting the previous installation of `diffview` and re-installing with it just as a dependency of `gitlab.nvim`.

Here's what the config looks like in my packer.lua file:
```
    use {
        'harrisoncramer/gitlab.nvim',
        requires = {
            "MunifTanjim/nui.nvim",
            "nvim-lua/plenary.nvim",
            "sindrets/diffview.nvim",
            "stevearc/dressing.nvim", -- Recommended but not required. Better UI for pickers.
            "nvim-tree/nvim-web-devicons", -- Recommended but not required. Icons in discussion tree.
        },
        run = function() require("gitlab.server").build(true) end,
        config = function()
            require("gitlab").setup()
        end,
```

I thought I could ignore it, but I also noticed that when I attempt to create keymap for (or run) the `review` command I get the following error (which seems related):

```
Error detected while processing :source (no file):
E5108: Error executing lua [string ":source (no file)"]:9: attempt to index global 'gitlab' (a nil value)
stack traceback:
        [string ":source (no file)"]:9: in main chunk
```

Any idea what I could be doing incorrectly?

**Comment by harrisoncramer** [comment]
This looks specifically like an issue with Packer, I'm not a user but would appreciate any help from the community...

Looks like diffview expects there to be a global variable `DiffviewGlobal` available when it's run, however for some reason it's not getting picked up. You can replicate this by using Packer's minimal configuration with this plugin.

**Comment by harrisoncramer** [comment]
For anyone else running into this issue, you have to require Diffview before you require Gitlab due to an issue in that repository and Packer: 

```lua
require("diffview") -- We require some global state from diffview
local gitlab = require("gitlab")
-- Your keybindings here...
```
