### ISSUE TITLE
Change default behaviour of delete comment

### ISSUE THREAD

**Issue by DanieleIsoni** [harrisoncramer/gitlab.nvim#96]
Hello,

When calling the delete_comment in the discussion tree vim asks you to answer the following propmt:
```Type number and <Enter> or click with the mouse (q or empty cancels)```

If pressing `<esc>` or `q` or leaving empty based on the prompt one would think it would cancel the action, instead it confirms the deletion, which is quite confusing.

So, I propose to change in the linked snippet the callback to the `vim.ui.select` like this:
```
function(choice)
    if choice == "Confirm" then 
        M.send_deletion(tree, unlinked)
    end 
end
```
https://github.com/harrisoncramer/gitlab.nvim/blob/deed861871e74ec523ac5872786dbfdeab78ec70/lua/gitlab/actions/discussions.lua#L544-L554

**Comment by harrisoncramer** [comment]
Yes, good call, that's definitely a bug. Do you want to open up a PR making this change?
